import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const extensionRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const css = fs.readFileSync(path.join(extensionRoot, "media", "main.css"), "utf8");
const html = fs.readFileSync(path.join(extensionRoot, "src", "previewPanel.ts"), "utf8");
const script = fs.readFileSync(path.join(extensionRoot, "media", "main.js"), "utf8");
const inputRouter = fs.readFileSync(path.join(extensionRoot, "media", "canvas-input.mjs"), "utf8");
const horizontalWheel = fs.readFileSync(path.join(extensionRoot, "media", "horizontal-wheel.mjs"), "utf8");
const extension = fs.readFileSync(path.join(extensionRoot, "src", "extension.ts"), "utf8");
const visualizationProvider = fs.readFileSync(path.join(extensionRoot, "src", "visualizationProvider.ts"), "utf8");
const gitSnapshots = fs.readFileSync(path.join(extensionRoot, "src", "gitSnapshots.ts"), "utf8");
const genericHover = css.indexOf("button:hover:not(:disabled)");
const activeLoopHover = css.indexOf('#loop[aria-pressed="true"]:hover:not(:disabled)');

assert.ok(genericHover >= 0, "generic button hover style must exist");
assert.ok(activeLoopHover > genericHover, "active LOOP hover must override the generic hover state");
assert.match(css.slice(activeLoopHover, css.indexOf("}", activeLoopHover) + 1), /background:\s*var\(--toolbar-hover\)/);
assert.match(css.slice(activeLoopHover, css.indexOf("}", activeLoopHover) + 1), /color:\s*var\(--code\)/);
assert.match(html, /id="range-in"/);
assert.match(html, /id="range-out"/);
assert.match(html, /id="range-clear"/);
assert.match(script, /advancePlaybackTime/);
assert.match(script, /saveThumbnailGif\(thumbnailRuntime, controller\.signal, range\)/);
assert.match(css, /\.timeline::before\s*\{[^}]*--range-end/s);
assert.match(html, /id="canvas-wrap"[^>]*data-fit="true"/);
assert.match(html, /id="stage-resizer"[^>]*role="separator"[^>]*aria-orientation="horizontal"[^>]*aria-valuemin="64"/);
assert.match(html, /MAX_THUMBNAIL_BYTES\s*=\s*20\s*\*\s*1024\s*\*\s*1024/);
assert.match(script, /canvasWrap\.dataset\.fit/);
assert.match(css, /\.canvas-wrap\[data-fit="true"\]\s*\{[^}]*overflow:\s*hidden/s);
assert.match(script, /createCanvasInputRouter\(\{[\s\S]*wheelTarget:\s*canvasWrap,[\s\S]*keyTarget:\s*window/);
assert.match(script, /onSample:\s*\(sample\)\s*=>\s*vscode\.postMessage\(\{[\s\S]*type:\s*"sample",[\s\S]*sceneId,[\s\S]*version:\s*sceneVersion,[\s\S]*sample/);
assert.match(inputRouter, /type:\s*"wheel"[\s\S]*if \(result\.handled\)[\s\S]*if \(!isFit\?\.\(\) \|\| inputModifiers\(event\) !== 0\) return;[\s\S]*previewWheel\?\.\(event\)/);
assert.match(inputRouter, /if \(isFit\?\.\(\) && runtime && !isBusy\?\.\(\) && event\.button === 1\)[\s\S]*kind:\s*"preview-pan"/);
assert.match(script, /previewPanX \+= dx;\s*previewPanY \+= dy;/s);
assert.match(script, /const fitScale = fitPreviewScale\([\s\S]*setPreviewScale\(wheelPreviewScale\(previewScale, deltaY, fitScale\), \{clientX, clientY, fit: true\}\)/);
assert.match(script, /runtime\.draw\(canvas, currentTime, renderPixelRatio\)/);
assert.match(script, /previewRenderPixelRatio\([\s\S]*window\.devicePixelRatio \|\| 1/);
assert.match(css, /\.canvas-wrap\[data-fit="true"\] canvas\[data-dragging="true"\]\s*\{[^}]*cursor:\s*grabbing/s);
assert.match(css, /\.menu-panel\s*\{[^}]*position:\s*fixed[^}]*overflow-y:\s*auto/s);
assert.match(css, /\.menu-panel\s*\{[^}]*width:\s*min\(174px,[^}]*padding:\s*2px;/s);
assert.match(html, /<details class="menu-submenu" data-positioned="false">[\s\S]*?<span>Stat<\/span>[\s\S]*?<span>Speed<\/span>[\s\S]*?data-speed="1"[\s\S]*?data-speed="2"/);
assert.match(html, /<span>Camera<\/span>[\s\S]*?data-camera="view2d"[\s\S]*?data-camera="view3d"[\s\S]*?data-camera="reset"/);
assert.match(html, /<span>Show Lines<\/span><output id="source-lines-value">5<\/output>[\s\S]*?data-source-lines="5"[^>]*aria-current="true"[^>]*disabled[\s\S]*?data-source-lines="10"[\s\S]*?data-source-lines="20"/);
assert.match(html, /<span>Document<\/span>[\s\S]*?class="menu-direct-actions"[^>]*aria-label="Canvas display"[\s\S]*?id="fit-mode"[^>]*>CANVAS TO FIT WINDOW[\s\S]*?id="actual-mode"[^>]*>CANVAS TO RAW SIZE[\s\S]*?id="preview-reset"[^>]*>RESET LAYOUT/);
assert.doesNotMatch(html, /id="canvas-fullscreen"|id="canvas-windowed"/);
assert.match(css, /\.menu-submenu > summary\s*\{[^}]*user-select:\s*none;/s);
assert.match(css, /\.menu-submenu > summary > span,\s*\.menu-submenu > summary > output\s*\{[^}]*pointer-events:\s*none;/s);
assert.match(css, /\.submenu-panel\s*\{[^}]*position:\s*fixed;[^}]*width:\s*min\(152px,[^}]*grid-template-columns:\s*1fr;/s);
assert.match(css, /\.menu-submenu\[open\]\[data-positioned="false"\] > \.submenu-panel\s*\{[^}]*visibility:\s*hidden/s);
assert.match(script, /function syncSubmenuPlacement\(submenu\)[\s\S]*cascadingMenuPlacement\([\s\S]*submenu\.dataset\.positioned = "true"/);
assert.match(script, /function resetPreviewTransform\(\) \{\s*if \(previewFits\) fitPreview\(\);\s*else setPreviewScale\(1, \{preserveAnchor: false\}\);\s*\}/s);
assert.match(script, /function resetCanvasView\(\) \{[\s\S]*manualStageHeightValue = null;[\s\S]*syncNormalLayoutLimit\(\);[\s\S]*resetPreviewTransform\(\);[\s\S]*\}/);
assert.match(script, /function resetCanvasView\(\)[\s\S]*if \(viewerLayout === "wide"\) syncWidePlayerWidth\(\);\s*else syncNormalLayoutLimit\(\);/);
assert.match(script, /previewResetButton\.addEventListener\("click", \(\) => \{\s*resetCanvasView\(\);\s*closePlayerMenu\(\);\s*\}\)/s);
assert.match(script, /stageResizer\.addEventListener\("pointerdown"[\s\S]*setPointerCapture[\s\S]*setManualStageHeight/);
assert.match(script, /stageResizer\.addEventListener\("pointermove"[\s\S]*event\.pointerId !== stageResizePointerId[\s\S]*setManualStageHeight/);
assert.match(script, /stageResizer\.addEventListener\("keydown"[\s\S]*"ArrowUp", "ArrowDown"[\s\S]*setManualStageHeight/);
assert.match(script, /function syncNormalLayoutLimit\(\) \{\s*if \(canvasFullscreen \|\| viewerLayout === "wide" \|\| manualStageHeightValue !== null\) return;/s);
assert.match(script, /function syncViewerLayout\(\)[\s\S]*responsiveViewerLayout\(window\.innerWidth, viewerLayout, forceCompactLayout\)[\s\S]*document\.body\.dataset\.layout = viewerLayout/);
assert.match(script, /const wideResizeEnabled = viewerLayout === "wide" && !canvasFullscreen;[\s\S]*wideResizer\.tabIndex = wideResizeEnabled \? 0 : -1/);
assert.doesNotMatch(script, /responsiveViewerLayout\(window\.innerWidth, sceneWidth/);
assert.match(script, /stageResizer\.addEventListener\("pointerdown", \(event\) => \{\s*if \(canvasFullscreen \|\| event\.button !== 0\) return;/s);
assert.doesNotMatch(html, /<summary><span>Canvas<\/span>/);
assert.doesNotMatch(html, /id="canvas-mode"/);
assert.match(css, /\.menu-direct-actions\s*\{[^}]*grid-template-columns:\s*1fr;[^}]*border-top:\s*1px solid var\(--line\)/s);
assert.doesNotMatch(script, /canvasMode/);
assert.match(html, /<span>Option<\/span><output id="option-value">DISABLED<\/output>[\s\S]*?data-auto-play-next="true"[^>]*>AUTO-PLAY NEXT ENABLE[\s\S]*?data-auto-play-next="false"[^>]*disabled>AUTO-PLAY NEXT DISABLE[\s\S]*?data-force-compact="true"[^>]*>COMPACT LAYOUT ENABLE[\s\S]*?data-force-compact="false"[^>]*disabled>COMPACT LAYOUT DISABLE/);
assert.doesNotMatch(html, /data-source-navigation|REVEAL SOURCE/);
assert.match(css, /\.option-group \+ \.option-group\s*\{[^}]*border-top:\s*1px solid var\(--line\)/s);
assert.match(css, /\.option-group\s*\{[^}]*grid-template-columns:\s*1fr/s);
assert.match(html, /<span>Document<\/span>[\s\S]*?id="open-lua"[\s\S]*?id="open-source"[\s\S]*?id="refresh"/);
assert.match(html, /<span>Stat<\/span><output id="stat-value">DISABLED<\/output>[\s\S]*?data-stat="true"[^>]*>ENABLE[\s\S]*?data-stat="false"[^>]*disabled>DISABLE/);
assert.doesNotMatch(html, /id="manual-indicator"|>MANUAL<\/span>/);
assert.match(html, /id="canvas-stat">— × — · — FPS/);
assert.match(script, /let showStats = persistedPreviewState\?\.showStats === true/);
assert.match(script, /function syncCanvasStat\(\)[\s\S]*stageResizer\.dataset\.stats = String\(showStats\)[\s\S]*canvasStat\.textContent/);
assert.match(script, /for \(const submenu of menuSubmenus\)[\s\S]*candidate !== submenu[\s\S]*candidate\.open = false/);
assert.doesNotMatch(html, /LIVE\s*\/\s*UNSAVED SYNC/);
assert.doesNotMatch(html, /id="zoom-(?:out|in|fit|actual)"/);
assert.match(html, /id="player-menu"[^>]*data-positioned="false"/);
assert.match(html, /id="series-menu"[^>]*data-positioned="false"/);
assert.match(css, /\.player-menu\[open\]\[data-positioned="false"\]\s*>\s*\.menu-panel[\s\S]*\.series-menu\[open\]\[data-positioned="false"\]\s*>\s*\.series-panel\s*\{[^}]*visibility:\s*hidden/s);
assert.match(script, /prepareMenuPlacement\(playerMenu, playerMenuTrigger, \(\) => \{[\s\S]*playerMenuAnchor = undefined;[\s\S]*syncPlayerMenuPlacement\(\);[\s\S]*\}\)/);
assert.match(script, /prepareMenuPlacement\(seriesMenu, seriesMenuTrigger, syncSeriesMenuPlacement\)/);
assert.match(script, /playerMenu\.addEventListener\("toggle", \(\) => \{[\s\S]*seriesMenu\.open = false;[\s\S]*syncOpenedMenuPlacement\(playerMenu, syncPlayerMenuPlacement\)/);
assert.match(script, /seriesMenu\.addEventListener\("toggle", \(\) => \{[\s\S]*playerMenu\.open = false;[\s\S]*syncOpenedMenuPlacement\(seriesMenu, syncSeriesMenuPlacement\)/);
assert.match(inputRouter, /listen\(canvas, "contextmenu", \(event\) => \{\s*event\.preventDefault\(\);\s*contextMenu\?\.\(event\);/s);
assert.match(script, /contextMenu:\s*\(event\) => \{[\s\S]*playerMenuAnchor = \{x: event\.clientX, y: event\.clientY\};[\s\S]*syncPlayerMenuPlacement\(\);[\s\S]*playerMenu\.open = true;/);
assert.match(inputRouter, /const result = dispatchPointer\("pointerdown"[\s\S]*if \(result\.capture\)[\s\S]*if \(result\.handled \|\| result\.capture \|\| result\.release\)[\s\S]*if \(runtime\.cameraMode !== "interactive"\) return;/);
assert.match(script, /redraw:\s*\(\) => \{\s*syncCamera\(\);\s*if \(!playing\) draw\(\);/s);
assert.match(script, /fetch\(config\.headingFont\)/);
assert.match(script, /candidate\.font\("IBM Plex Sans KR", headingFontBytes, "ttf"\)/);
assert.match(script, /fetch\(config\.serifHeadingFont\)/);
assert.match(script, /candidate\.font\("Source Serif 4", serifHeadingFontBytes, "ttf"\)/);
assert.match(css, /\.document\s*\{[^}]*font-family:\s*"Source Serif 4",\s*"IBM Plex Sans KR",\s*var\(--font\)/s);
assert.match(css, /--content-inline:\s*8px;/);
assert.match(css, /--document-inline:\s*14px;/);
assert.match(css, /--font:\s*"Source Serif 4",\s*"IBM Plex Sans KR",\s*var\(--vscode-font-family,\s*serif\)/);
assert.match(css, /--mono:\s*"Source Serif 4",\s*"IBM Plex Sans KR",\s*var\(--vscode-editor-font-family,\s*monospace\)/);
assert.match(css, /--paper:\s*var\(--vscode-editor-background,\s*#ffffff\)/);
assert.match(css, /--text:\s*var\(--vscode-foreground,\s*#555b64\)/);
assert.match(css, /--muted:\s*var\(--vscode-descriptionForeground,\s*#7a8089\)/);
assert.match(css, /--code:\s*var\(--vscode-textLink-foreground,\s*#9b3600\)/);
assert.match(css, /--icon:\s*var\(--vscode-icon-foreground/);
assert.match(css, /--toolbar-hover:\s*var\(--vscode-toolbar-hoverBackground/);
assert.match(css, /--toolbar-hover-outline:\s*var\(--vscode-toolbar-hoverOutline/);
assert.match(css, /--toolbar-active:\s*var\(--vscode-toolbar-activeBackground/);
assert.match(css, /--inline-code-background:\s*var\(--vscode-textCodeBlock-background/);
assert.match(css, /body\.vscode-dark[\s\S]*color-scheme:\s*dark/);
assert.match(css, /canvas\s*\{[^}]*background:\s*transparent/s);
assert.match(css, /canvas\s*\{[^}]*touch-action:\s*none/s);
assert.doesNotMatch(css, /canvas\s*\{[^}]*--vscode-/s);
assert.doesNotMatch(css, /data-vscode-theme-id/);
assert.match(css, /\.transport\s*\{[^}]*padding:\s*5px var\(--content-inline\);/s);
assert.match(css, /\.transport\s*\{[^}]*position:\s*relative;[^}]*z-index:\s*2;[^}]*background:\s*var\(--paper\)/s);
assert.doesNotMatch(css, /\.transport\s*\{[^}]*border-bottom:/s);
assert.match(css, /\.player\s*\{[^}]*border-bottom:\s*1px solid var\(--line\);/s);
assert.match(css, /\.document-header\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\);[^}]*padding:\s*4px var\(--document-inline\) 3px;/s);
assert.doesNotMatch(css, /\.document-header\s*\{[^}]*border-bottom:/s);
assert.match(css, /\.description-section\s*\{[^}]*margin:\s*0;[^}]*padding:\s*4px var\(--document-inline\) 1px;/s);
assert.match(css, /\.canvas-viewport\s*\{[^}]*padding:\s*0;/s);
assert.match(css, /\.player\[data-stage-sizing="manual"\] \.stage-shell\s*\{[^}]*height:\s*var\(--manual-stage-height\)[^}]*aspect-ratio:\s*auto/s);
assert.match(css, /\.stage-resizer\s*\{[^}]*height:\s*7px[^}]*cursor:\s*ns-resize/s);
assert.doesNotMatch(css, /\.stage-resizer\[data-manual="true"\]::before|#manual-indicator/);
assert.match(css, /\.stage-resizer\[data-stats="true"\] #canvas-stat\s*\{[^}]*display:\s*inline/s);
assert.match(css, /\.markdown-body\s*>\s*:first-child\s*\{[^}]*margin-top:\s*0/s);
assert.doesNotMatch(css, /@media \(max-width: 600px\)[\s\S]*?\.document-header\s*\{[^}]*padding-top/s);
assert.match(html, /<section class="player"[\s\S]*<footer class="transport">[\s\S]*<\/footer>\s*<section class="wide-series-slot"[\s\S]*<\/section>\s*<\/section>\s*<div class="wide-resizer"[\s\S]*<article class="document-body">/);
assert.match(css, /--normal-stage-max-height:\s*max\(0px,\s*calc\(100vh - 45px\)\)/);
assert.match(css, /html\s*\{[^}]*height:\s*100%;[^}]*margin:\s*0;[^}]*padding:\s*0;[^}]*overflow:\s*hidden/s);
assert.match(css, /body\s*\{[^}]*height:\s*100%;[^}]*margin:\s*0;[^}]*padding:\s*0;[^}]*overflow:\s*hidden/s);
assert.match(css, /\.viewer\s*\{[^}]*display:\s*grid;[^}]*height:\s*100%;[^}]*grid-template-rows:\s*auto minmax\(0, 1fr\);[^}]*overflow:\s*hidden/s);
assert.match(css, /\.player\s*\{[^}]*position:\s*relative;[^}]*margin:\s*0;[^}]*padding:\s*0/s);
assert.match(css, /\.document-body\s*\{[^}]*display:\s*grid;[^}]*min-height:\s*0;[^}]*grid-template-rows:\s*auto minmax\(0, 1fr\);[^}]*padding:\s*0;[^}]*overflow:\s*hidden/s);
assert.match(css, /body\[data-layout="wide"\] \.viewer\s*\{[^}]*grid-template-columns:[^}]*7px[^}]*minmax\(280px, 1fr\);[^}]*grid-template-rows:\s*minmax\(0, 1fr\)/s);
assert.match(html, /id="wide-resizer"[^>]*role="separator"[^>]*aria-orientation="vertical"/);
assert.match(html, /id="wide-resizer"[^>]*aria-valuemin="280"/);
assert.match(css, /body\[data-layout="wide"\] \.wide-resizer\s*\{[^}]*display:\s*block[^}]*cursor:\s*ew-resize/s);
assert.match(css, /body\[data-layout="wide"\] \.player\s*\{[^}]*grid-template-rows:\s*minmax\(0, 1fr\) auto auto;[^}]*border-right:\s*0;[^}]*border-bottom:\s*0/s);
assert.match(css, /body\[data-layout="wide"\] \.player\[data-stage-sizing="manual"\]\s*\{[^}]*grid-template-rows:\s*var\(--manual-stage-height\) auto auto minmax\(0, 1fr\)/s);
assert.match(css, /body\[data-layout="wide"\] \.player\[data-series-docked="true"\]\[data-stage-sizing="manual"\]\s*\{[^}]*grid-template-rows:\s*var\(--manual-stage-height\) auto auto minmax\(0, 1fr\)/s);
assert.match(css, /\.stage-shell\s*\{[^}]*aspect-ratio:\s*var\(--scene-aspect-ratio, 16 \/ 9\)/s);
assert.doesNotMatch(script, /stageShell\.style\.aspectRatio/);
assert.match(script, /setProperty\("--scene-aspect-ratio", `\$\{width\} \/ \$\{height\}`\)/);
assert.match(script, /wideResizer\.addEventListener\("pointerdown"[\s\S]*setManualWidePlayerWidth/);
assert.match(css, /body\[data-layout="wide"\] \.document-header\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\);[^}]*padding-top:\s*8px/s);
assert.match(css, /#inspector-content\s*\{[^}]*min-height:\s*0;[^}]*overflow-x:\s*hidden;[^}]*overflow-y:\s*auto;[^}]*scrollbar-gutter:\s*stable/s);
assert.doesNotMatch(css, /#inspector-content::-webkit-scrollbar:horizontal/);
assert.match(script, /useVerticalWheelForHorizontalScroll\(seriesGroupItems\)/);
assert.doesNotMatch(script, /useVerticalWheelForHorizontalScroll\(inspectorContent\)/);
assert.match(horizontalWheel, /scrollWidth\s*<=\s*element\.clientWidth\s*\+\s*1[\s\S]*scrollHeight\s*>\s*element\.clientHeight\s*\+\s*1/);
assert.match(horizontalWheel, /element\.addEventListener\("wheel", onWheel, \{passive: false\}\)/);
assert.match(html, /id="document-name"[\s\S]*id="inspector-content"[\s\S]*id="notes-item"[\s\S]*>NOTES<[\s\S]*id="description-content"[\s\S]*id="code-content"/);
assert.doesNotMatch(html, /id="inspector-tabs"|id="code-tab"|id="notes-tab"|id="code-panel"|id="notes-panel"/);
assert.match(script, /syncSourceInspector\(scene\.sourceContexts, scene\.activeSourceIndex/);
assert.match(script, /event\.data\?\.type === "sourceContexts"[\s\S]*preserveSelection: true/);
assert.match(script, /text\.textContent\s*=\s*row\.text/);
assert.doesNotMatch(script, /openSourceOnClick|setOpenSourceOnClick|sourceClickNavigationButtons/);
assert.match(script, /let autoPlayNext = typeof persistedPreviewState\?\.autoPlayNext === "boolean"[\s\S]*config\.autoPlayNext === true/);
assert.match(script, /type: "setAutoPlayNext", enabled: autoPlayNext/);
assert.match(script, /let forceCompactLayout = typeof persistedPreviewState\?\.forceCompactLayout === "boolean"[\s\S]*config\.forceCompactLayout === true/);
assert.match(script, /type: "setForceCompactLayout", enabled: forceCompactLayout/);
assert.match(script, /let sourceContextLineCount = normalizedSourceContextLineCount\([\s\S]*persistedPreviewState\?\.sourceContextLineCount \?\? config\.sourceContextLineCount/);
assert.match(script, /sourceContextExpansionCount\(context, direction, sourceContextLineCount\)/);
assert.match(script, /type: "setSourceContextLineCount", count: sourceContextLineCount/);
assert.match(script, /function syncSourceContextLineCount\(\)[\s\S]*sourceLinesValue\.textContent[\s\S]*button\.disabled = current/);
assert.doesNotMatch(html, /OPEN_SOURCE_ON_CLICK_STATE_KEY|openSourceOnClick|setOpenSourceOnClick|data-source-navigation/);
assert.match(html, /AUTO_PLAY_NEXT_STATE_KEY\s*=\s*"autoPlayNext"/);
assert.match(html, /FORCE_COMPACT_LAYOUT_STATE_KEY\s*=\s*"forceCompactLayout"/);
assert.match(html, /SOURCE_CONTEXT_LINE_COUNT_STATE_KEY\s*=\s*"sourceContextLineCount"/);
assert.match(html, /globalState\.get<boolean>\(AUTO_PLAY_NEXT_STATE_KEY, false\)/);
assert.match(html, /globalState\.get<boolean>\(FORCE_COMPACT_LAYOUT_STATE_KEY, false\)/);
assert.match(html, /globalState\.get<number>\(SOURCE_CONTEXT_LINE_COUNT_STATE_KEY\)/);
assert.match(html, /message\.type === "setAutoPlayNext"[\s\S]*typeof message\.enabled === "boolean"[\s\S]*globalState\.update\(AUTO_PLAY_NEXT_STATE_KEY, message\.enabled\)/);
assert.match(html, /message\.type === "setForceCompactLayout"[\s\S]*typeof message\.enabled === "boolean"[\s\S]*globalState\.update\(FORCE_COMPACT_LAYOUT_STATE_KEY, message\.enabled\)/);
assert.match(html, /message\.type === "setSourceContextLineCount"[\s\S]*isSourceContextLineCount\(message\.count\)[\s\S]*globalState\.update\(SOURCE_CONTEXT_LINE_COUNT_STATE_KEY, message\.count\)/);
assert.match(script, /item\.addEventListener\("toggle"[\s\S]*openSourceKeys\.delete\(sourceKey\)[\s\S]*type: "resetSourceContext"[\s\S]*openSourceKeys\.add\(sourceKey\)[\s\S]*activeSourceIndex = index;[\s\S]*renderSourceExcerpt\(excerpt, context, index\)/);
assert.match(script, /const see = document\.createElement\("button"\);[\s\S]*see\.className = "reference-see";[\s\S]*see\.textContent = "SEE"/);
assert.match(script, /see\.addEventListener\("click", \(event\) => \{[\s\S]*event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*activeSourceIndex = index;[\s\S]*vscode\.postMessage\(\{type: "openRelatedSource", index\}\)/);
assert.doesNotMatch(script, /item\.addEventListener\("toggle"[\s\S]*notesItem\.open = false/);
assert.match(script, /notesItem\.addEventListener\("toggle", \(\) => \{\s*notesOpen = notesItem\.open;\s*\}\)/);
assert.match(script, /function openSeriesItem\(groupIndex, itemIndex\)[\s\S]*type: "openSeries", groupIndex, itemIndex/);
assert.doesNotMatch(script, /type: "openSeries", groupIndex, itemIndex, openSource/);
assert.doesNotMatch(html, /message\.openSource|private async openSeries\([^)]*openSource/);
assert.doesNotMatch(css, /\.reference-item\[open\] > \.reference-summary > \.reference-summary-content\s*\{[^}]*box-shadow:/s);
assert.match(html, /sourceContexts,[\s\S]*activeSourceIndex:\s*sourceContexts\.length \? 0 : -1/);
assert.match(html, /function sourceReferenceIdentity\(source: PreviewSourceReference\): string[\s\S]*source\.uri\.toString\(\)[\s\S]*source\.range/);
assert.match(html, /function sourceReferenceIds\(sources: readonly PreviewSourceReference\[\]\): string\[\][\s\S]*const identity = sourceReferenceIdentity\(source\);[\s\S]*return `\$\{identity\}:\$\{occurrence\}`/);
assert.doesNotMatch(html, /sourceHighlightDecoration|editor\.setDecorations\(/);
assert.match(html, /private sourceOpenGeneration = 0/);
assert.match(html, /const generation = \+\+this\.sourceOpenGeneration;[\s\S]*generation === this\.sourceOpenGeneration && callerCurrent\(\)/);
assert.match(html, /scheduleSourceContextUpdate\(\)/);
assert.match(html, /type: "sourceContexts"/);
assert.match(html, /if \(source\.range && !location\)[\s\S]*unavailable: true/);
assert.doesNotMatch(html, /isWholeLine:\s*true/);
assert.doesNotMatch(css, /\.player\s*\{[^}]*position:\s*sticky/s);
assert.match(script, /layoutObserver\.observe\(stageShell\)/);
assert.doesNotMatch(html, /id="source-links"|id="source-link-items"/);
assert.match(html, /class="series-navigation"[\s\S]*id="series-previous"[\s\S]*id="series-menu"[\s\S]*id="series-position"[\s\S]*id="series-next"/);
assert.match(html, /id="inspector-content"[^>]*aria-label="Notes and related source contexts"/);
assert.doesNotMatch(html, /id="inspector-content"[^>]*role="list"|id="notes-item"[^>]*role="listitem"|id="code-content"[^>]*role="group"/);
assert.doesNotMatch(script, /item\.setAttribute\("role", "listitem"\)|excerpt\.setAttribute\("role", "table"\)|line\.setAttribute\("role", "row"\)/);
assert.doesNotMatch(css, /\.code-line\s*\{[^}]*(?:background|box-shadow):/s);
assert.match(css, /\.code-line-focus\s*\{[^}]*box-shadow:\s*inset 2px 0 var\(--focus\);[^}]*background:\s*var\(--vscode-editor-lineHighlightBackground, transparent\)/s);
assert.match(script, /function renderSourceAccordion\(sourceScrollPositions = new Map\(\)\)[\s\S]*item\.className = "reference-item source-reference-item"[\s\S]*summary\.className = "reference-summary"[\s\S]*excerpt\.className = "reference-code"/);
assert.match(script, /summaryContent\.className = "reference-summary-content"[\s\S]*summaryContent\.append\(chevron, label\)[\s\S]*summary\.append\(summaryContent\)/);
assert.match(script, /codeFrame\.className = "reference-code-frame"[\s\S]*codeHeader\.className = "reference-code-header"[\s\S]*codeHeader\.append\(location[\s\S]*see\)[\s\S]*codeFrame\.append\(codeHeader, excerpt\)[\s\S]*item\.append\(summary, codeFrame\)/);
assert.match(script, /context\.kind === "diff"[\s\S]*reference-diff-indicator[\s\S]*reference-diff-added[\s\S]*reference-diff-removed/);
assert.match(html, /class="reference-summary notes-summary"[\s\S]*class="reference-summary-content"[\s\S]*>NOTES</);
assert.doesNotMatch(css, /grid-template-columns:\s*minmax\(100cqw, max-content\)/);
assert.match(css, /\.reference-item\s*\{[^}]*width:\s*100%;[^}]*min-width:\s*0;[^}]*max-width:\s*100%/s);
assert.match(css, /\.reference-summary\s*\{[^}]*width:\s*100%;[^}]*min-width:\s*0;[^}]*max-width:\s*100%;[^}]*border:\s*0/s);
assert.match(css, /\.reference-summary-content\s*\{[^}]*display:\s*grid;[^}]*width:\s*100%;[^}]*grid-template-columns:\s*12px minmax\(0, 1fr\)/s);
assert.doesNotMatch(css, /#code-content > \.reference-item:last-child > \.reference-summary|\.reference-item\.last-item > \.reference-summary/);
assert.match(css, /\.reference-code-frame\s*\{[^}]*padding-left:\s*18px/s);
assert.match(css, /\.reference-code-header\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto auto;[^}]*background:\s*var\(--diff-context\)/s);
assert.match(css, /\.reference-code-header::before\s*\{[^}]*border-left:\s*1px solid var\(--line\);[^}]*border-bottom:\s*1px solid var\(--line\)/s);
assert.match(css, /\.reference-see\s*\{[^}]*margin-left:\s*auto;[^}]*background:\s*transparent;/s);
assert.match(css, /\.reference-diff-added\s*\{[^}]*vscode-gitDecoration-addedResourceForeground/s);
assert.match(css, /\.reference-diff-removed\s*\{[^}]*vscode-gitDecoration-deletedResourceForeground/s);
assert.match(script, /const lines = `\$\{context\.focusStartLine\}–\$\{context\.focusEndLine\}`/);
assert.match(script, /if \(context\.hasMoreAbove\)[\s\S]*sourceExpansionButton\(excerpt, context, index, "above"\)[\s\S]*if \(context\.hasMoreBelow\)[\s\S]*sourceExpansionButton\(excerpt, context, index, "below"\)/);
assert.match(script, /type: "expandSourceContext",\s*sceneId,\s*index,\s*id: context\.id,\s*direction/);
assert.match(script, /sourceContextRowIsFocused\(context, row\.lineNumber\)[\s\S]*line\.classList\.add\("code-line-focus"\)/);
assert.match(script, /pendingSourceExpansionAnchor = \{[\s\S]*line: anchorLine,[\s\S]*top: anchor\?\.getBoundingClientRect\(\)\.top/);
assert.match(script, /function restoreSourceExpansionAnchor\(\)[\s\S]*excerpt\.scrollTop \+= line\.getBoundingClientRect\(\)\.top - anchor\.top/);
assert.match(html, /SOURCE_CONTEXT_LINE_COUNTS = \[5, 10, 20\] as const/);
assert.match(html, /DEFAULT_SOURCE_CONTEXT_LINE_COUNT: SourceContextLineCount = 5/);
assert.match(html, /const step = sourceContextLineCount\([\s\S]*direction === "above" \? step[\s\S]*direction === "below" \? step/);
assert.match(html, /focusStartLine:[\s\S]*focusEndLine:[\s\S]*totalLineCount:[\s\S]*hasMoreAbove:[\s\S]*hasMoreBelow:/);
assert.match(html, /message\.type === "expandSourceContext"[\s\S]*message\.sceneId === this\.sceneId[\s\S]*typeof message\.id === "string"[\s\S]*message\.direction === "above" \|\| message\.direction === "below"/);
assert.match(html, /message\.type === "resetSourceContext"[\s\S]*message\.sceneId === this\.sceneId[\s\S]*await this\.resetSourceContext/);
assert.match(html, /sourceReferenceIds\(references\)\[index\] !== id/);
assert.match(css, /\.code-expand\s*\{[^}]*position:\s*sticky;[^}]*height:\s*24px;[^}]*background:\s*var\(--diff-context\)/s);
assert.doesNotMatch(script, /candidate !== item\) candidate\.open = false/);
assert.match(script, /const sourceHighlightGenerations = new WeakMap\(\)/);
assert.match(script, /function refreshOpenSourceHighlights\(\)[\s\S]*querySelectorAll\("\.reference-item\[open\]"\)/);
assert.match(script, /function referenceSummaryTitle\(label, open\) \{\s*if \(open\) return `Collapse \$\{label\}`;/);
assert.match(script, /item\.addEventListener\("toggle", \(\) => \{\s*summary\.title = referenceSummaryTitle\(summary\.dataset\.label, item\.open\);/);
assert.doesNotMatch(script, /seriesMenu\.hidden\s*=\s*groups\.length/);
assert.match(script, /seriesItems\.dataset\.empty\s*=\s*String\(groups\.length === 0\)/);
assert.match(script, /seriesPosition\.textContent = hasActiveItem \? `\$\{activeItem \+ 1\}\/\$\{itemCount\}` : "—"/);
assert.match(html, /id="series-groups"[\s\S]*id="series-items"/);
assert.match(html, /<section class="wide-series-slot" id="wide-series-slot"[^>]*hidden><\/section>/);
assert.equal((html.match(/class="series-panel"/g) ?? []).length, 1, "Wide must reuse the existing series panel");
assert.match(html, /id="open-lua"[\s\S]*id="open-source"/);
assert.match(html, /id="loop"[^>]*aria-label="Enable loop"[^>]*>[\s\S]*class="control-icon loop-icon"[\s\S]*<\/button>/);
assert.doesNotMatch(script, /loopButton\.textContent/);
assert.match(html, /id="play"[^>]*>[\s\S]*class="control-icon play-icon"[\s\S]*class="control-icon pause-icon"/);
assert.match(html, /id="restart"[^>]*>[\s\S]*class="control-icon restart-icon"/);
assert.match(script, /playIcon\.toggleAttribute\("hidden", playing\)/);
assert.match(script, /pauseIcon\.toggleAttribute\("hidden", !playing\)/);
assert.doesNotMatch(script, /playIcon\.hidden|pauseIcon\.hidden/);
assert.match(script, /playButton\.dataset\.state\s*=\s*playing \? "playing" : "paused"/);
assert.doesNotMatch(script, /playButton\.textContent/);
assert.match(html, /aria-label="Player settings"[^>]*>[\s\S]*class="control-icon settings-icon"[\s\S]*<\/summary>/);
assert.match(html, /id="series-previous"[^>]*aria-label="Previous series item"[^>]*disabled/);
assert.match(html, /id="series-next"[^>]*aria-label="Next series item"[^>]*disabled/);
assert.match(script, /seriesPreviousButton\.addEventListener\("click"[\s\S]*seriesStepTarget\(currentSeries, -1\)[\s\S]*openSeriesItem\(target\.groupIndex, target\.itemIndex\)/);
assert.match(script, /seriesNextButton\.addEventListener\("click"[\s\S]*seriesStepTarget\(currentSeries, 1\)[\s\S]*openSeriesItem\(target\.groupIndex, target\.itemIndex\)/);
assert.match(script, /const autoAdvanceTarget = autoAdvanceSeriesTarget\(currentSeries, autoPlayNext\)[\s\S]*looping && !autoAdvanceTarget[\s\S]*if \(next\.ended\)[\s\S]*openSeriesItem\(autoAdvanceTarget\.groupIndex, autoAdvanceTarget\.itemIndex\)/);
assert.match(css, /\.series-navigation > button\s*\{[^}]*min-width:\s*26px;[^}]*min-height:\s*26px;[^}]*padding:\s*0;/s);
assert.match(css, /@media \(max-width: 420px\)[\s\S]*\.series-navigation > button\s*\{[^}]*display:\s*none/s);
assert.match(html, /aria-label="Open animation series"[^>]*>[\s\S]*class="control-icon series-icon"[\s\S]*<\/summary>/);
assert.match(css, /\.settings-icon\s*\{[^}]*width:\s*17px;[^}]*height:\s*17px;/s);
assert.match(css, /#loop\[aria-pressed="true"\]\s*\{[^}]*background:\s*transparent;[^}]*color:\s*var\(--code\)/s);
assert.match(css, /#loop\[aria-pressed="true"\]::after\s*\{[^}]*border-radius:\s*50%;[^}]*background:\s*currentColor/s);
assert.match(css, /\.primary-controls \.play\[data-state="playing"\]\s*\{[^}]*color:\s*var\(--code\)/s);
assert.match(css, /\.play-icon,[\s\S]*\.pause-icon\s*\{[^}]*fill:\s*currentColor;[^}]*stroke:\s*none/s);
assert.match(css, /\.reference-summary\s*\{[^}]*width:\s*100%;[^}]*background:\s*var\(--paper\)/s);
assert.match(css, /\.reference-code\s*\{[^}]*width:\s*100%;[^}]*min-width:\s*0;[^}]*max-width:\s*100%;[^}]*max-height:\s*clamp\(120px, 38vh, 360px\);[^}]*overflow:\s*auto;[^}]*overscroll-behavior:\s*contain/s);
assert.match(css, /\.reference-code::-webkit-scrollbar:vertical\s*\{[^}]*width:\s*6px/s);
assert.match(css, /body\[data-layout="wide"\] \.document-header\s*\{[^}]*padding-top:\s*8px;[^}]*padding-bottom:\s*8px/s);
assert.match(css, /\.menu-panel\s*\{[^}]*background:\s*linear-gradient\([\s\S]*var\(--paper\)/s);
assert.match(css, /\.submenu-panel\s*\{[^}]*background:\s*linear-gradient\([\s\S]*var\(--paper\)/s);
assert.match(css, /body\[data-layout="wide"\] \.wide-resizer\s*\{[^}]*z-index:\s*9/s);
assert.match(script, /const sourceScrollPositions = preserveSelection[\s\S]*left:\s*excerpt\?\.scrollLeft[\s\S]*top:\s*excerpt\?\.scrollTop[\s\S]*renderSourceAccordion\(sourceScrollPositions\)/);
assert.match(script, /function renderSourceAccordion\(sourceScrollPositions = new Map\(\)\)[\s\S]*excerpt\.scrollLeft = scrollPosition\?\.left \?\? 0;[\s\S]*excerpt\.scrollTop = scrollPosition\?\.top \?\? 0/);
assert.match(script, /function restoreSourceExpansionAnchor\(\)[\s\S]*const excerpt = item\?\.querySelector\("\.reference-code"\)[\s\S]*excerpt\.scrollTop \+= line\.getBoundingClientRect\(\)\.top - anchor\.top/);
assert.match(script, /context\.kind === "diff"[\s\S]*code-line-diff[\s\S]*code-line-number-old[\s\S]*code-line-number-new[\s\S]*code-line-marker/);
assert.match(script, /context\.kind === "diff" \? "DIFF UNAVAILABLE" : "SOURCE CONTEXT UNAVAILABLE"/);
assert.match(css, /\.code-line-diff\s*\{[^}]*grid-template-columns:[^}]*minmax\(34px, auto\)[^}]*minmax\(34px, auto\)/s);
assert.match(css, /\.code-line-inserted\s*\{[^}]*--vscode-diffEditor-insertedLineBackground/s);
assert.match(css, /\.code-line-removed\s*\{[^}]*--vscode-diffEditor-removedLineBackground/s);
assert.match(html, /if \(source\.diff\) \{[\s\S]*this\.sourceContextExpansion\.get\(id\)[\s\S]*expandedRange[\s\S]*verifiedGitDiff\(document, diff, expandedRange\)/);
assert.match(html, /kind: "diff",[\s\S]*hasMoreAbove: startLine > 1,[\s\S]*hasMoreBelow: endLine < document\.lineCount,[\s\S]*expanded: expansion\.above > 0 \|\| expansion\.below > 0/);
assert.match(html, /openVerifiedGitDiff\([\s\S]*document,[\s\S]*diff,[\s\S]*range,[\s\S]*this\.sourceTargetColumn\(\)/);
assert.match(gitSnapshots, /getExtension<GitExtension>\("vscode\.git"\)/);
assert.match(gitSnapshots, /repository\.state\.HEAD\?\.commit\?\.toLowerCase\(\) !== diff\.head/);
assert.match(gitSnapshots, /repository\.getCommit\(diff\.base\)[\s\S]*repository\.getObjectDetails\(diff\.base, diff\.oldUri\.fsPath\)/);
assert.match(gitSnapshots, /diff\.oldUri\.toString\(\) !== document\.uri\.toString\(\)[\s\S]*added: true/);
assert.match(gitSnapshots, /function isUnknownGitPath[\s\S]*gitErrorCode === "UnknownPath"/);
assert.match(gitSnapshots, /addedFileRowsForRange\([\s\S]*resolved\.headSource,[\s\S]*range\.startLine,[\s\S]*range\.endLine/);
assert.match(gitSnapshots, /repository\.diffBlobs\([\s\S]*`\$\{diff\.base\}:\$\{oldPath\}`,[\s\S]*`\$\{diff\.head\}:\$\{currentPath\}`[\s\S]*\)/);
assert.match(gitSnapshots, /normalizedGitSource\(document\.getText\(\)\) !== normalizedGitSource\(headSource\)/);
assert.match(gitSnapshots, /api\.toGitUri\(diff\.oldUri, diff\.base\)[\s\S]*"vscode\.diff"[\s\S]*document\.uri/);
assert.doesNotMatch(script, /descriptionCharacterCount|LONG_DESCRIPTION_CHARACTER_THRESHOLD|WIDE_SERIES_MIN_HEIGHT/);
assert.doesNotMatch(script, /renderedDescriptionLineCount/);
assert.match(script, /type:\s*"openSeries"/);
assert.match(script, /type:\s*"openSeries",\s*groupIndex,\s*itemIndex/);
assert.match(html, /Number\.isInteger\(message\.groupIndex\)[\s\S]*Number\.isInteger\(message\.itemIndex\)/);
assert.match(script, /type:\s*"openLua"/);
assert.match(script, /String\(itemIndex \+ 1\)\.padStart\(2, "0"\)/);
assert.doesNotMatch(html, /await this\.openSource\(\s*context\.relatedSources\[0\] \?\? context\.primarySource/s);
assert.match(css, /\.series-panel\s*\{[^}]*position:\s*fixed[^}]*overflow:\s*hidden/s);
assert.match(css, /\.series-groups\s*\{[^}]*overflow-x:\s*auto[^}]*scrollbar-width:\s*none/s);
assert.match(css, /\.series-groups::-webkit-scrollbar\s*\{[^}]*display:\s*none/s);
assert.match(css, /\.series-items\s*\{[^}]*overflow-y:\s*auto/s);
assert.match(css, /body\[data-layout="wide"\] \.player\[data-series-docked="true"\]\s*\{[^}]*grid-template-rows:\s*minmax\(0, 1fr\) auto auto minmax\(92px, 0\.38fr\)/s);
assert.match(css, /body\[data-layout="wide"\] \.wide-series-slot\s*\{[^}]*display:\s*grid;[^}]*overflow:\s*hidden/s);
assert.match(css, /body\[data-layout="wide"\] \.wide-series-slot > \.series-panel\s*\{[^}]*position:\s*static;[^}]*width:\s*100%;[^}]*height:\s*100%;[^}]*box-shadow:\s*none/s);
assert.match(css, /\.player\s*\{[^}]*container-name:\s*player;[^}]*container-type:\s*inline-size/s);
assert.match(css, /@container player \(max-width:\s*520px\)\s*\{[\s\S]*?\.series-navigation > button\s*\{[^}]*display:\s*none/s);
assert.match(css, /@container player \(max-width:\s*360px\)\s*\{[\s\S]*?#time\s*\{[^}]*display:\s*none/s);
assert.match(script, /function syncSeriesPanelHost\(\)[\s\S]*wideSeriesSlot\.append\(seriesPanel\)[\s\S]*hostSeriesPanelInPopup\(\)/);
assert.match(script, /function hostSeriesPanelInPopup\(\)[\s\S]*seriesMenu\.append\(seriesPanel\);[\s\S]*wideSeriesSlot\.hidden = true;[\s\S]*delete player\.dataset\.seriesDocked;[\s\S]*if \(manualStageHeightValue !== null\) applyManualStageHeight\(\);/);
assert.match(script, /function syncSeriesPanelHost\(\)[\s\S]*groups\.length > 0\s*&& !seriesMenu\.open;[\s\S]*wideSeriesSlot\.append\(seriesPanel\)[\s\S]*hostSeriesPanelInPopup\(\)/);
assert.doesNotMatch(script, /requestAnimationFrame\(applyManualStageHeight\)/);
assert.match(script, /function setCanvasFullscreen\(enabled\)[\s\S]*syncSeriesPanelHost\(\);\s*if \(!canvasFullscreen\) \{\s*if \(viewerLayout === "wide"\) syncWidePlayerWidth\(\);\s*if \(manualStageHeightValue !== null\) applyManualStageHeight\(\);\s*else if \(viewerLayout === "compact"\) syncNormalLayoutLimit\(\);\s*\}[\s\S]*requestAnimationFrame\(\(\) => \{\s*fitPreview\(\);/);
assert.match(html, /private sourceShowQueue: Promise<void> = Promise\.resolve\(\)/);
assert.match(html, /private sourceTargetColumn\(\): vscode\.ViewColumn[\s\S]*this\.panel\.viewColumn[\s\S]*previewColumn \+ 1/);
assert.match(html, /vscode\.window\.tabGroups\.all\.find\(\(group\) => group\.viewColumn === nextColumn\)/);
assert.doesNotMatch(html, /viewColumn:\s*this\.sourceColumn \?\? vscode\.ViewColumn\.One/);
assert.match(html, /viewColumn: options\.preservePreview\s*\? this\.sourceTargetColumn\(\)\s*: this\.sourceColumn \?\? vscode\.ViewColumn\.One/);
assert.match(html, /editor\.revealRange\(location\.range, vscode\.TextEditorRevealType\.InCenter\)/);
assert.match(html, /const pending = this\.sourceShowQueue\.then\(show, show\);\s*this\.sourceShowQueue = pending\.then\(\(\) => undefined, \(\) => undefined\);\s*await pending;/);
assert.match(script, /seriesMenuTrigger\.addEventListener\("click", \(\) => \{\s*if \(player\.dataset\.seriesDocked !== "true"\) return;\s*hostSeriesPanelInPopup\(\);\s*\}, \{capture: true\}\)/);
assert.doesNotMatch(script, /seriesMenuTrigger\.addEventListener\("click", \(event\) =>/);
assert.match(script, /seriesMenu\.addEventListener\("toggle", \(\) => \{[\s\S]*if \(seriesMenu\.open\) revealActiveSeriesItem\(\);\s*else syncSeriesPanelHost\(\);/);
assert.match(script, /useVerticalWheelForHorizontalScroll\(canvasWrap, \(\) => canvasWrap\.dataset\.fit !== "true"\)/);
assert.doesNotMatch(visualizationProvider, /label:\s*"Animation Lua"/);
assert.match(visualizationProvider, /visualizationSeriesGroups\(entries\)/);
assert.match(visualizationProvider, /async previewContextForAnimation\(/);
assert.match(extension, /visualizations\.previewContextForAnimation/);
assert.match(html, /previewContext \?\? await this\.contextResolver\?\.\(document, sourceColumn\)/);

console.log("player control states passed");
