-- Reference study: front-to-back BVH traversal rejects whole triangle sets
-- with ray/AABB tests before evaluating leaf triangles.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={6.2,4.2,7.2},target={0,0,0},up={0,1,0},projection="perspective",fov=0.62,near=0.1,far=35}}
local space=spatial:space {x={-4,4,1},y={-2.5,2.5,1},z={-3,3,1},opacity=0.12,id="bvh:space"}
local function box(parent,id,lo,hi,color)
 local v={{lo[1],lo[2],lo[3]},{hi[1],lo[2],lo[3]},{hi[1],hi[2],lo[3]},{lo[1],hi[2],lo[3]},{lo[1],lo[2],hi[3]},{hi[1],lo[2],hi[3]},{hi[1],hi[2],hi[3]},{lo[1],hi[2],hi[3]}};local e={{1,2},{2,3},{3,4},{4,1},{5,6},{6,7},{7,8},{8,5},{1,5},{2,6},{3,7},{4,8}};local g=parent:group {id=id};local lines={};for i,x in ipairs(e)do lines[i]=g:line {from=v[x[1]],to=v[x[2]],color=color,width=1.7,id=id..":e"..i}end;return g,lines
end
local root,rootLines=box(space,"bvh:root",{-2.9,-1.4,-1.7},{2.9,1.5,1.7},"border");local left,leftLines=box(space,"bvh:left",{-2.9,-1.3,-1.5},{-0.15,1.35,1.5},"accent");local right,rightLines=box(space,"bvh:right",{0.10,-1.4,-1.7},{2.9,1.5,1.7},"focus")
local triangles={space:polygon {points={{-2.5,-0.9,-0.6},{-0.7,-0.8,0.5},{-1.4,1.0,0.1}},fill="#4fc1ff35",stroke="accent",width=2,id="bvh:tri:left"},space:polygon {points={{0.5,-0.8,-0.4},{2.4,-0.7,0.3},{1.35,1.05,0.15}},fill="#8b5cf64d",stroke="focus",width=2,id="bvh:tri:right"}}
local origin={-4.0,0.15,0.35};local hit={1.34,0.08,0.12};local ray=space:line {from=origin,to={3.3,0.05,0.02},color="warning",width=4,layer=8,id="bvh:ray"};local originPoint=space:point {point=origin,radius=8,fill="warning",layer=10,id="bvh:origin"};local hitPoint=space:point {point=hit,radius=9,fill="result",stroke="background",width=1.4,layer=12,id="bvh:hit"};local hitLabel=space:text {text="nearest hit",point={1.34,0.42,0.12},role="code",fill="result",layer=20,id="bvh:hit-label"}
spatial:create(space,0.28,"ease_out");spatial:draw_border_then_fill(triangles,0.52,"ease_out",0.08);spatial:create(rootLines,0.46,"ease_out",0.02);spatial:create(originPoint,0.20,"ease_out");spatial:wait(0.38);spatial:create(ray,0.76,"linear");local rootChanges={};for _,line in ipairs(rootLines)do rootChanges[#rootChanges+1]={target=line,stroke="warning"}end;spatial:play(rootChanges,0.28,"gentle",0);local rootReady=spatial:duration();local childLines={};for _,line in ipairs(leftLines)do childLines[#childLines+1]=line end;for _,line in ipairs(rightLines)do childLines[#childLines+1]=line end;spatial:create(childLines,0.55,"ease_out",0.02);spatial:fade(left,0.20,0.40,"gentle");local rejectReady=spatial:duration();local rightChanges={};for _,line in ipairs(rightLines)do rightChanges[#rightChanges+1]={target=line,stroke="result"}end;spatial:play(rightChanges,0.32,"gentle",0);spatial:create(hitPoint,0.24,"ease_out");spatial:fade_in(hitLabel,{duration=0.22,curve="gentle"});local hitReady=spatial:duration();spatial:wait(2.0);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local rows={ledger:text {text="BVH · NEAR FIRST",point={0,3.05},role="h3",fill="foreground",id="bvh:ledger-title"},ledger:text {text="pop root\nAABB hit: t=[1.1, 6.8]",point={-2.70,2.12},align={0,0.5},role="code",fill="warning",id="bvh:row-root"},ledger:text {text="left child: miss\nreject all 1 triangle",point={-2.70,0.82},align={0,0.5},role="code",fill="muted",id="bvh:row-left"},ledger:text {text="right child: hit\npush near leaf first",point={-2.70,-0.42},align={0,0.5},role="code",fill="focus",id="bvh:row-right"},ledger:text {text="triangle test → t = 5.34",point={-2.70,-1.62},align={0,0.5},role="code",fill="result",id="bvh:row-hit"},ledger:text {text="2 AABB tests\n1 triangle test instead of 2",point={0,-2.70},role="code",fill="result",id="bvh:result"}}
ledger:fade_in(rows[1],{duration=0.25,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(ledger,rootReady-0.35);ledger:fade_in(rows[2],{duration=0.35,curve="gentle"});waitUntil(ledger,rejectReady-0.45);ledger:fade_in(rows[3],{duration=0.30,curve="gentle"});ledger:fade_in(rows[4],{duration=0.30,curve="gentle"});waitUntil(ledger,hitReady-0.35);ledger:fade_in(rows[5],{duration=0.28,curve="gentle"});ledger:fade_in(rows[6],{duration=0.30,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="BVH traversal · reject geometry in groups",point={0,2.65},role="h2",fill="foreground",id="bvh:title"};local subtitle=page:text {text="ray/AABB intervals choose the next node before any leaf triangle test",point={0,2.25},role="text",fill="muted",id="bvh:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
