-- Reference study: one immutable mesh buffer is paired with several model
-- matrices; geometry data is not duplicated by the draw description.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local function matrix(x,y,z,s)local c=math.cos(y*0.35);local q=math.sin(y*0.35);return{s*c,0,s*q,x,0,s,0,y,-s*q,0,s*c,z,0,0,0,1}end
local base={{0,0.72,0},{-0.62,-0.52,-0.48},{0.62,-0.52,-0.48},{0,-0.52,0.68}};local faces={{1,2,3},{1,3,4},{1,4,2},{2,4,3}}
local poses={{-2.2,-0.55,1.3,0.72},{0,-0.55,1.5,0.88},{2.1,-0.55,1.0,0.64},{-1.55,0.15,-1.2,0.58},{0.5,0.05,-1.4,0.76},{2.35,0.30,-1.7,0.52},{-0.35,1.00,-3.1,0.48},{1.55,1.05,-3.2,0.44}}
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={6.2,4.5,7.4},target={0,0,-0.8},up={0,1,0},projection="perspective",fov=0.64,near=0.1,far=35}}
local space=spatial:space {x={-4,4,1},y={-2,3,1},z={-4,3,1},opacity=0.11,id="instance:space"}
local groups,allFaces={},{},{};allFaces={}
for i,p in ipairs(poses)do local g=space:group {id="instance:"..i};groups[i]=g;for j,f in ipairs(faces)do allFaces[#allFaces+1]=g:polygon {points={base[f[1]],base[f[2]],base[f[3]]},fill=i%2==0 and "#8b5cf64c" or "#4fc1ff4c",stroke="border",width=1,id="instance:"..i..":face:"..j}end end
local sourceLabel=space:text {text="shared mesh buffer",point={0,1.18,0},role="code",fill="warning",layer=20,id="instance:source-label"}
spatial:create(space,0.28,"ease_out");spatial:draw_border_then_fill(allFaces,0.62,"ease_out",0.006);spatial:fade_in(sourceLabel,{duration=0.24,curve="gentle"});spatial:wait(0.52);local distributeStart=spatial:duration();local changes={};for i,p in ipairs(poses)do changes[#changes+1]={target=groups[i],transform=matrix(p[1],p[2],p[3],p[4])}end;changes[#changes+1]={target=sourceLabel,opacity=0};spatial:play(changes,1.25,"ease_in_out",0);local distributed=spatial:duration();for _,g in ipairs(groups)do spatial:indicate(g,{scale=1.02,duration=0.12,curve="gentle"})end;spatial:wait(1.9);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local items={ledger:text {text="INSTANCED DRAW",point={0,3.02},role="h3",fill="foreground",id="instance:ledger-title"},ledger:text {text="vertex buffer: 4 vertices\nindex buffer: 4 triangles",point={-2.70,2.02},align={0,0.5},role="code",fill="accent",id="instance:mesh-data"},ledger:text {text="instance buffer",point={-2.70,0.78},align={0,0.5},role="h3",fill="focus",id="instance:buffer-title"},ledger:text {text="M0  M1  M2  M3\nM4  M5  M6  M7",point={-2.70,0.08},align={0,0.5},role="code",fill="foreground",id="instance:matrices"},ledger:text {text="vertex = M[instanceID] · p",point={-2.70,-1.00},align={0,0.5},role="code",fill="warning",id="instance:formula"},ledger:text {text="1 mesh upload\n8 model transforms\n1 instanced draw",point={0,-2.25},role="code",fill="result",id="instance:result"}}
ledger:fade_in(items[1],{duration=0.25,curve="gentle"});ledger:fade_in(items[2],{duration=0.32,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(ledger,distributeStart);ledger:fade_in(items[3],{duration=0.24,curve="gentle"});ledger:fade_in(items[4],{duration=0.28,curve="gentle"});ledger:fade_in(items[5],{duration=0.28,curve="gentle"});waitUntil(ledger,distributed);ledger:fade_in(items[6],{duration=0.34,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="Mesh instancing · one mesh, eight transforms",point={0,2.65},role="h2",fill="foreground",id="instance:title"};local subtitle=page:text {text="instanceID selects transform data while every copy reuses the same vertices",point={0,2.25},role="text",fill="muted",id="instance:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
