-- Reference study: one CCD pass rotates a three-bone character chain from the
-- distal pivot toward the root while preserving every bone length.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local function add(a,b)return{a[1]+b[1],a[2]+b[2],a[3]+b[3]}end
local function sub(a,b)return{a[1]-b[1],a[2]-b[2],a[3]-b[3]}end
local function scale(v,s)return{v[1]*s,v[2]*s,v[3]*s}end
local function dot(a,b)return a[1]*b[1]+a[2]*b[2]+a[3]*b[3]end
local function length(v)return math.sqrt(dot(v,v))end
local function normalize(v)local n=length(v);assert(n>1e-9,"zero vector");return scale(v,1/n)end
local function cross(a,b)return{a[2]*b[3]-a[3]*b[2],a[3]*b[1]-a[1]*b[3],a[1]*b[2]-a[2]*b[1]}end
local function rotateAround(p,pivot,angle)local d=sub(p,pivot);local c,s=math.cos(angle),math.sin(angle);return add(pivot,{c*d[1]-s*d[2],s*d[1]+c*d[2],d[3]})end
local function frameFromX(origin,direction)local x=normalize(direction);local helper=math.abs(x[2])>0.92 and {0,0,1} or {0,1,0};local z=normalize(cross(x,helper));local y=cross(z,x);return{x[1],y[1],z[1],origin[1],x[2],y[2],z[2],origin[2],x[3],y[3],z[3],origin[3],0,0,0,1}end
local lengths={1.28,1.04,0.82};local base={-1.55,-0.65,0};local initialAngles={math.rad(18),math.rad(24),math.rad(-20)};local target={1.12,1.24,0}
local points={base};local total=0;for i,L in ipairs(lengths)do total=total+initialAngles[i];points[i+1]=add(points[i],{L*math.cos(total),L*math.sin(total),0})end
local states={{points={points[1],points[2],points[3],points[4]},pivot=0,angle=0,residual=length(sub(points[4],target))}}
local current={points[1],points[2],points[3],points[4]}
for pivot=3,1,-1 do local pv=current[pivot];local toEnd=sub(current[4],pv);local toTarget=sub(target,pv);local angle=math.atan(toEnd[1]*toTarget[2]-toEnd[2]*toTarget[1],dot(toEnd,toTarget));angle=math.max(math.rad(-72),math.min(math.rad(72),angle));for i=pivot+1,4 do current[i]=rotateAround(current[i],pv,angle)end;local copy={current[1],current[2],current[3],current[4]};states[#states+1]={points=copy,pivot=pivot,angle=angle,residual=length(sub(copy[4],target))}end
assert(states[#states].residual<states[1].residual,"CCD pass must reduce residual");for _,state in ipairs(states)do for i,L in ipairs(lengths)do assert(math.abs(length(sub(state.points[i+1],state.points[i]))-L)<1e-8,"CCD preserves bone lengths")end end
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={4.5,3.0,6.4},target={0,0.3,0},up={0,1,0},projection="perspective",fov=0.60,near=0.1,far=25}}
local space=spatial:space {x={-2.5,2.6,1},y={-2.1,2.4,1},z={-2,2,1},opacity=0.14,id="ik:space"}
local function bone(parent,id,a,b)local d=sub(b,a);local L=length(d);local g=parent:group {matrix=frameFromX(a,d),id=id};local waist=L*0.43;local r=math.min(0.16,L*0.17);local ring={{waist,r,0},{waist,0,r},{waist,-r,0},{waist,0,-r}};local fs={};for i=1,4 do local j=i%4+1;fs[#fs+1]=g:polygon {points={{0,0,0},ring[i],ring[j]},fill="#4fc1ff62",stroke="foreground",width=1,id=id..":a:"..i};fs[#fs+1]=g:polygon {points={{L,0,0},ring[j],ring[i]},fill="#8b5cf652",stroke="foreground",width=1,id=id..":b:"..i}end;return g,fs end
local bones,faces={},{};for i=1,3 do local g,fs=bone(space,"ik:bone:"..i,states[1].points[i],states[1].points[i+1]);bones[i]=g;for _,f in ipairs(fs)do faces[#faces+1]=f end end
local joints={};for i,p in ipairs(states[1].points)do joints[i]=space:point {point=p,radius=i==4 and 9 or 7,fill=i==4 and "result" or "surface",stroke="accent",width=2,layer=10,id="ik:j"..(i-1)}end
local targetPoint=space:point {point=target,radius=11,fill="warning",stroke="background",width=1.5,layer=11,id="ik:target"};local targetLabel=space:text {text="target",point=add(target,{0.18,0.24,0}),align={0,0.5},role="code",fill="warning",layer=20,id="ik:target-label"};local residualLine=space:line {from=states[1].points[4],to=target,color="danger",width=3,dash={7,5},layer=8,id="ik:residual"}
spatial:create(space,0.28,"ease_out");spatial:draw_border_then_fill(faces,0.58,"ease_out",0.02);spatial:create(joints,0.32,"ease_out",0.04);spatial:create(targetPoint,0.24,"ease_out");spatial:fade_in(targetLabel,{duration=0.18,curve="gentle"});spatial:create(residualLine,0.36,"ease_out");spatial:wait(0.48)
local stepTimes={};local currentPoints=states[1].points
for step=2,#states do local state=states[step];stepTimes[#stepTimes+1]=spatial:duration();spatial:indicate(joints[state.pivot],{scale=1.08,duration=0.28,curve="gentle"});local changes={};for i=state.pivot,3 do changes[#changes+1]={target=bones[i],transform=frameFromX(state.points[i],sub(state.points[i+1],state.points[i]))}end;for i=state.pivot+1,4 do changes[#changes+1]={target=joints[i],shift=sub(state.points[i],currentPoints[i])}end;changes[#changes+1]={target=residualLine,opacity=0};spatial:play(changes,0.76,"ease_in_out",0);local newResidual=space:line {from=state.points[4],to=target,color=step==#states and "result" or "danger",width=3,dash={7,5},layer=8,id="ik:residual:"..step};spatial:create(newResidual,0.24,"ease_out");residualLine=newResidual;currentPoints=state.points;spatial:wait(0.24)end
local solved=spatial:duration();spatial:indicate(joints[4],{scale=1.08,duration=0.36,curve="gentle"});spatial:wait(2.0);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local titleL=ledger:text {text="CCD · DISTAL → ROOT",point={0,3.02},role="h3",fill="foreground",id="ik:ledger-title"};ledger:fade_in(titleL,{duration=0.25,curve="gentle"});local rows={};for i=2,#states do local s=states[i];local y=2.05-(i-2)*1.12;rows[i-1]=ledger:text {text=string.format("pivot J%d   Δθ=%+.1f°\nresidual = %.3f",s.pivot-1,math.deg(s.angle),s.residual),point={-2.68,y},align={0,0.5},role="code",size=11,fill=i==#states and "result" or "foreground",id="ik:row:"..i}end;local invariant=ledger:text {text="each pivot rotates its suffix\nbone lengths remain constant",point={0,-1.78},role="code",fill="warning",id="ik:invariant"};local result=ledger:text {text=string.format("%.3f → %.3f",states[1].residual,states[#states].residual),point={0,-2.72},role="h3",fill="result",id="ik:result"};local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;for i,row in ipairs(rows)do waitUntil(ledger,stepTimes[i]);ledger:fade_in(row,{duration=0.32,curve="gentle"})end;waitUntil(ledger,solved-0.35);ledger:fade_in(invariant,{duration=0.30,curve="gentle"});ledger:fade_in(result,{duration=0.34,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="Inverse kinematics · CCD reaches a target",point={0,2.65},role="h2",fill="foreground",id="ik:title"};local subtitle=page:text {text="distal-to-root pivots rotate only their descendant bones",point={0,2.25},role="text",fill="muted",id="ik:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
