-- Reference study: one concept camera classifies object bounds by frustum
-- visibility and projected radius, selecting high/medium/low topology.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={7.2,5.0,7.4},target={0,0,-2.2},up={0,1,0},projection="perspective",fov=0.64,near=0.1,far=40}}
local space=spatial:space {x={-5,5,1},y={-2.5,3.5,1},z={-8,3,1},opacity=0.10,id="lod:space"}
local camera={0,1.45,2.3};local planeZ=1.0;local plane={space:polygon {points={{-1.15,0.70,planeZ},{1.15,0.70,planeZ},{1.15,2.20,planeZ},{-1.15,2.20,planeZ}},fill="#ffd86614",stroke="warning",width=1.5,id="lod:near-plane"}}
local frustum={};for _,p in ipairs({{-4,-1.3,-8},{4,-1.3,-8},{4,3.0,-8},{-4,3.0,-8}})do frustum[#frustum+1]=space:line {from=camera,to=p,color="warning",width=1.3,id="lod:frustum:"..#frustum+1}end
local camPoint=space:point {point=camera,radius=9,fill="warning",layer=10,id="lod:camera"};local camLabel=space:text {text="camera",point={0,1.85,2.3},role="code",fill="warning",layer=20,id="lod:camera-label"}
local function makeObject(id,center,level,color)
 local g=space:group {id=id};local x,y,z=center[1],center[2],center[3];local top={x,y+0.78,z};local bottom={x,y-0.78,z};local ring={};local segments=level=="HIGH" and 8 or level=="MED" and 4 or 3;for i=0,segments-1 do local t=2*math.pi*i/segments;ring[#ring+1]={x+0.68*math.cos(t),y,z+0.68*math.sin(t)}end;local faces={};for i=1,segments do local j=i%segments+1;faces[#faces+1]=g:polygon {points={top,ring[i],ring[j]},fill=color,stroke="border",width=1,id=id..":top:"..i};faces[#faces+1]=g:polygon {points={bottom,ring[j],ring[i]},fill=color,stroke="border",width=1,id=id..":bottom:"..i}end;local label=g:text {text=level,point={x,y+1.05,z},role="code",fill=color,layer=20,id=id..":label"};return g,faces,label,#faces end
local specs={{"near",{-0.9,0,-0.3},"HIGH","accent",126},{"mid",{1.0,0,-3.1},"MED","focus",54},{"far",{-0.6,0,-6.3},"LOW","result",18},{"outside",{4.5,0,-3.0},"CULLED","muted",0}}
local groups,faces,labels={}, {}, {};local totalFaces=0
for i,s in ipairs(specs)do local g,f,l,count=makeObject("lod:"..s[1],s[2],s[3],s[4]);groups[i]=g;labels[i]=l;totalFaces=totalFaces+count;for _,v in ipairs(f)do faces[#faces+1]=v end end
spatial:create(space,0.28,"ease_out");spatial:create({camPoint,plane[1]},0.40,"ease_out",0.08);spatial:create(frustum,0.52,"ease_out",0.04);spatial:fade_in(camLabel,{duration=0.18,curve="gentle"});spatial:draw_border_then_fill(faces,0.78,"ease_out",0.008);for _,v in ipairs(labels)do spatial:fade_in(v,{duration=0.12,curve="gentle"})end;local classifyReady=spatial:duration();spatial:fade(groups[4],0.12,0.42,"gentle");spatial:indicate(groups[1],{scale=1.03,duration=0.32,curve="gentle"});spatial:wait(2.0);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local rows={{"near","rpx = 126 → HIGH","accent"},{"mid","rpx = 54 → MED","focus"},{"far","rpx = 18 → LOW","result"},{"outside","frustum miss → CULLED","muted"}};local rowGroups={};for i,r in ipairs(rows)do local y=2.45-(i-1)*1.08;local g=ledger:group {id="lod:row:"..i};g:text {text=r[1],point={-2.72,y+0.20},align={0,0.5},role="h3",fill=r[3],id="lod:row-title:"..i};g:text {text=r[2],point={-2.72,y-0.25},align={0,0.5},role="code",size=11,fill="foreground",id="lod:row-value:"..i};rowGroups[i]=g end;local rule=ledger:text {text="visible first\nprojected radius selects LOD",point={0,-2.22},role="code",fill="warning",id="lod:rule"}
ledger:fade_in(rowGroups[1],{duration=0.30,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(ledger,classifyReady-0.90);for i=2,4 do ledger:fade_in(rowGroups[i],{duration=0.28,curve="gentle"})end;ledger:fade_in(rule,{duration=0.30,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="Frustum culling and screen-space LOD",point={0,2.65},role="h2",fill="foreground",id="lod:title"};local subtitle=page:text {text="one camera chooses visibility first, then topology detail from projected size",point={0,2.25},role="text",fill="muted",id="lod:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
