-- Reference study: roughness changes a GGX Cook-Torrance response on every
-- face of an explicit indexed gem while N/L/V/H remain fixed at one sample.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local function add(a,b)return{a[1]+b[1],a[2]+b[2],a[3]+b[3]}end
local function sub(a,b)return{a[1]-b[1],a[2]-b[2],a[3]-b[3]}end
local function scale(v,s)return{v[1]*s,v[2]*s,v[3]*s}end
local function dot(a,b)return a[1]*b[1]+a[2]*b[2]+a[3]*b[3]end
local function cross(a,b)return{a[2]*b[3]-a[3]*b[2],a[3]*b[1]-a[1]*b[3],a[1]*b[2]-a[2]*b[1]}end
local function normalize(v)local n=math.sqrt(dot(v,v));assert(n>1e-9,"zero vector");return scale(v,1/n)end
local function clamp(x)return math.max(0,math.min(1,x))end
local function srgb(x)x=clamp(x);return x<=0.0031308 and 12.92*x or 1.055*x^(1/2.4)-0.055 end
local function hex(rgb)return string.format("#%02x%02x%02x",math.floor(srgb(rgb[1])*255+0.5),math.floor(srgb(rgb[2])*255+0.5),math.floor(srgb(rgb[3])*255+0.5))end
local vertices={{0,1.48,0}};local segments=6;for i=0,segments-1 do local t=2*math.pi*i/segments;vertices[#vertices+1]={1.08*math.cos(t),0.55,1.08*math.sin(t)}end;for i=0,segments-1 do local t=2*math.pi*(i+0.5)/segments;vertices[#vertices+1]={0.86*math.cos(t),-0.66,0.86*math.sin(t)}end;vertices[#vertices+1]={0,-1.42,0}
local indices={};for i=0,segments-1 do local u0=2+i;local u1=2+(i+1)%segments;local l0=2+segments+i;local l1=2+segments+(i+1)%segments;indices[#indices+1]={1,u0,u1};indices[#indices+1]={u0,l0,l1};indices[#indices+1]={u0,l1,u1};indices[#indices+1]={#vertices,l1,l0}end
local faces={};for _,idx in ipairs(indices)do local a,b,c=vertices[idx[1]],vertices[idx[2]],vertices[idx[3]];local center=scale(add(add(a,b),c),1/3);local n=normalize(cross(sub(b,a),sub(c,a)));if dot(n,center)<0 then b,c=c,b;n=normalize(cross(sub(b,a),sub(c,a)))end;faces[#faces+1]={points={a,b,c},center=center,normal=n}end
local light={2.40,2.60,2.00};local view={4.8,3.4,6.2};local base={0.08,0.34,0.72};local metallic=0.35;local roughA,roughB=0.18,0.62
local function evaluate(face,rough)
 local N=face.normal;local L=normalize(sub(light,face.center));local V=normalize(sub(view,face.center));local H=normalize(add(L,V));local nl=math.max(dot(N,L),0);local nv=math.max(dot(N,V),0);local nh=math.max(dot(N,H),0);local vh=math.max(dot(V,H),0);local alpha=rough*rough;local a2=alpha*alpha;local denom=math.pi*(nh*nh*(a2-1)+1)^2;local D=a2/math.max(denom,1e-6);local k=(rough+1)^2/8;local function g1(x)return x/(x*(1-k)+k)end;local G=g1(nl)*g1(nv);local F0={0.04*(1-metallic)+base[1]*metallic,0.04*(1-metallic)+base[2]*metallic,0.04*(1-metallic)+base[3]*metallic};local F={};for i=1,3 do F[i]=F0[i]+(1-F0[i])*(1-vh)^5 end;local color={};for i=1,3 do local spec=D*G*F[i]/math.max(4*nl*nv,1e-5);local kd=(1-F[i])*(1-metallic);local linear=0.025*base[i]+(kd*base[i]/math.pi+spec)*nl*2.2;color[i]=linear/(1+linear)end;return{N=N,L=L,V=V,H=H,D=D,G=G,F=(F[1]+F[2]+F[3])/3,color=hex(color)}
end
local selectedIndex,score=1,-1e9;local desired=normalize({0.7,0.45,1});for i,f in ipairs(faces)do local s=dot(f.normal,desired);if s>score then selectedIndex,score=i,s end end;local selected=faces[selectedIndex];local stateA,stateB=evaluate(selected,roughA),evaluate(selected,roughB);local colorsA,colorsB={},{};for i,f in ipairs(faces)do colorsA[i]=evaluate(f,roughA).color;colorsB[i]=evaluate(f,roughB).color end
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye=view,target={0,0.05,0},up={0,1,0},projection="perspective",fov=0.62,near=0.1,far=30}}
local space=spatial:space {x={-3,3.6,1},y={-2,3,1},z={-3,3.6,1},opacity=0.12,id="pbr:space"};local mesh=space:group {id="pbr:mesh"};local objects={};for i,f in ipairs(faces)do objects[i]=mesh:polygon {points=f.points,fill=colorsA[i],stroke=i==selectedIndex and "result" or "border",width=i==selectedIndex and 2.8 or 1,id="pbr:face:"..i}end;local sample=mesh:point {point=selected.center,radius=8,fill="result",stroke="background",width=1.4,layer=10,id="pbr:sample"}
local vectors={space:vector {origin=selected.center,value=scale(stateA.N,1.18),color="accent",width=4,tip=12,layer=12,id="pbr:N"},space:vector {origin=selected.center,value=scale(stateA.L,1.42),color="warning",width=4,tip=12,layer=12,id="pbr:L"},space:vector {origin=selected.center,value=scale(stateA.V,1.32),color="secondary",width=4,tip=12,layer=12,id="pbr:V"},space:vector {origin=selected.center,value=scale(stateA.H,1.62),color="success",width=4,tip=12,layer=12,id="pbr:H"}}
local vectorLabels={space:text {text="N",point=add(selected.center,scale(stateA.N,1.42)),role="code",fill="accent",layer=20,id="pbr:N-label"},space:text {text="L",point=add(selected.center,scale(stateA.L,1.64)),role="code",fill="warning",layer=20,id="pbr:L-label"},space:text {text="V",point=add(selected.center,scale(stateA.V,1.54)),role="code",fill="secondary",layer=20,id="pbr:V-label"},space:text {text="H",point=add(selected.center,scale(stateA.H,2.10)),role="code",fill="success",layer=20,id="pbr:H-label"}}
local lightPoint=space:point {point=light,radius=10,fill="warning",stroke="background",width=1.4,layer=10,id="pbr:light"};local lightLabel=space:text {text="area-light sample",point=add(light,{0,-0.38,0}),role="code",fill="warning",layer=20,id="pbr:light-label"}
spatial:create(space,0.28,"ease_out");spatial:draw_border_then_fill(objects,0.68,"ease_out",0.018);spatial:create(sample,0.22,"ease_out");spatial:create(lightPoint,0.24,"ease_out");spatial:fade_in(lightLabel,{duration=0.18,curve="gentle"});spatial:create(vectors,0.62,"ease_out",0.08);for _,label in ipairs(vectorLabels)do spatial:fade_in(label,{duration=0.12,curve="gentle"})end;spatial:wait(0.58);local roughStart=spatial:duration();local changes={};for i,o in ipairs(objects)do changes[#changes+1]={target=o,fill=colorsB[i]}end;spatial:play(changes,1.25,"ease_in_out",0);local roughEnd=spatial:duration();spatial:wait(2.1);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local items={ledger:text {text="GGX MICROFACETS",point={0,3.02},role="h3",fill="foreground",id="pbr:ledger-title"},ledger:text {text="specular = D · G · F / (4 N·L N·V)",point={-2.72,2.38},align={0,0.5},role="code",size=10.5,fill="foreground",id="pbr:formula"},ledger:text {text=string.format("roughness %.2f\nD %.3f   G %.3f   F %.3f",roughA,stateA.D,stateA.G,stateA.F),point={-2.72,1.35},align={0,0.5},role="code",fill="accent",id="pbr:state-a"},ledger:text {text="roughness changes α\n→ changes the microfacet lobe",point={-2.72,0.08},align={0,0.5},role="code",size=11,fill="warning",id="pbr:change"},ledger:text {text=string.format("roughness %.2f\nD %.3f   G %.3f   F %.3f",roughB,stateB.D,stateB.G,stateB.F),point={-2.72,-1.10},align={0,0.5},role="code",fill="result",id="pbr:state-b"},ledger:text {text="N, L, V, H stay fixed\nevery mesh face is re-evaluated",point={0,-2.55},role="code",fill="muted",id="pbr:invariant"}}
ledger:fade_in(items[1],{duration=0.25,curve="gentle"});ledger:fade_in(items[2],{duration=0.28,curve="gentle"});ledger:fade_in(items[3],{duration=0.34,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(ledger,roughStart-0.30);ledger:fade_in(items[4],{duration=0.30,curve="gentle"});ledger:fade_in(items[5],{duration=roughEnd-roughStart,curve="ease_out"});ledger:fade_in(items[6],{duration=0.30,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="PBR microfacets · roughness reshapes reflection",point={0,2.65},role="h2",fill="foreground",id="pbr:title"};local subtitle=page:text {text="GGX D, Smith G, and Schlick F re-evaluate every face on a real mesh",point={0,2.25},role="text",fill="muted",id="pbr:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
