-- Reference study: an organized point cloud keeps row/column adjacency, so
-- finite-difference tangents provide normals and deterministic triangles.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local function add(a,b)return{a[1]+b[1],a[2]+b[2],a[3]+b[3]}end
local function sub(a,b)return{a[1]-b[1],a[2]-b[2],a[3]-b[3]}end
local function scale(v,s)return{v[1]*s,v[2]*s,v[3]*s}end
local function dot(a,b)return a[1]*b[1]+a[2]*b[2]+a[3]*b[3]end
local function cross(a,b)return{a[2]*b[3]-a[3]*b[2],a[3]*b[1]-a[1]*b[3],a[1]*b[2]-a[2]*b[1]}end
local function normalize(v)local n=math.sqrt(dot(v,v));assert(n>1e-9,"zero vector");return scale(v,1/n)end
local cols,rows=11,8;local points={};local function index(c,r)return(r-1)*cols+c end
for r=1,rows do for c=1,cols do local x=-2.4+4.8*(c-1)/(cols-1);local z=-1.65+3.3*(r-1)/(rows-1);local y=0.34*math.sin(1.18*x)*math.cos(1.05*z);points[index(c,r)]={x,y,z}end end
local sc,sr=6,4;local center=points[index(sc,sr)];local tx=sub(points[index(sc+1,sr)],points[index(sc-1,sr)]);local tz=sub(points[index(sc,sr+1)],points[index(sc,sr-1)]);local normal=normalize(cross(tz,tx));assert(dot(normal,{0,1,0})>0,"normal must face upward")
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={5.3,3.7,6.1},target={0,0,0},up={0,1,0},projection="perspective",fov=0.61,near=0.1,far=30}}
local space=spatial:space {x={-3,3,1},y={-1.6,2.2,1},z={-2.5,2.5,1},opacity=0.12,id="surface:space"};local cloud={};for i,p in ipairs(points)do cloud[i]=space:point {point=p,radius=3.8,fill="accent",layer=8,id="surface:p:"..i}end
local neighborhood={};for _,cr in ipairs({{sc-1,sr},{sc+1,sr},{sc,sr-1},{sc,sr+1}})do neighborhood[#neighborhood+1]=space:point {point=points[index(cr[1],cr[2])],radius=7,fill="focus",layer=11,id="surface:neighbor:"..#neighborhood+1}end
local centerPoint=space:point {point=center,radius=9,fill="result",stroke="background",width=1.4,layer=12,id="surface:center"};local normalVector=space:vector {origin=center,value=scale(normal,1.25),color="warning",width=4,tip=13,layer=13,id="surface:normal"};local normalLabel=space:text {text="n = normalize(tz × tx)",point=add(center,scale(normal,1.48)),role="code",fill="warning",layer=20,id="surface:normal-label"}
local triangles={};for r=1,rows-1 do for c=1,cols-1 do local a=points[index(c,r)];local b=points[index(c+1,r)];local d=points[index(c,r+1)];local e=points[index(c+1,r+1)];triangles[#triangles+1]=space:polygon {points={a,b,e},fill="#4fc1ff20",stroke="border",width=0.8,id="surface:tri:"..#triangles+1};triangles[#triangles+1]=space:polygon {points={a,e,d},fill="#8b5cf620",stroke="border",width=0.8,id="surface:tri:"..#triangles+1}end end
spatial:create(space,0.28,"ease_out");spatial:create(cloud,0.56,"ease_out",0.006);local cloudReady=spatial:duration();spatial:create(neighborhood,0.34,"ease_out",0.05);spatial:create(centerPoint,0.24,"ease_out");spatial:create(normalVector,0.52,"ease_out");spatial:fade_in(normalLabel,{duration=0.22,curve="gentle"});local normalReady=spatial:duration();spatial:draw_border_then_fill(triangles,0.82,"ease_out",0.003);local cloudFade={};for _,point in ipairs(cloud)do cloudFade[#cloudFade+1]={target=point,opacity=0.24}end;spatial:play(cloudFade,0.38,"gentle",0);local surfaceReady=spatial:duration();spatial:look({view="3d",eye={5.7,2.45,6.4},target={0,0,0},up={0,1,0},projection="perspective",fov=0.61,near=0.1,far=30},1.10,"ease_in_out");spatial:wait(2.0);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local items={ledger:text {text="ORGANIZED CLOUD",point={0,3.02},role="h3",fill="foreground",id="surface:ledger-title"},ledger:text {text=string.format("%d × %d = %d points",cols,rows,#points),point={-2.70,2.34},align={0,0.5},role="code",fill="accent",id="surface:count"},ledger:text {text="neighbors keep row/column identity",point={-2.70,1.65},align={0,0.5},role="code",size=11,fill="focus",id="surface:adjacency"},ledger:text {text="tx = p[c+1] − p[c−1]\ntz = p[r+1] − p[r−1]",point={-2.70,0.65},align={0,0.5},role="code",size=10.5,fill="foreground",id="surface:tangents"},ledger:text {text=string.format("n = (%.2f, %.2f, %.2f)",normal[1],normal[2],normal[3]),point={-2.70,-0.38},align={0,0.5},role="code",fill="warning",id="surface:normal-value"},ledger:text {text=string.format("2(%d−1)(%d−1) = %d triangles",cols,rows,#triangles),point={-2.70,-1.32},align={0,0.5},role="code",fill="result",id="surface:tri-count"},ledger:text {text="points → neighborhood normal\n→ indexed surface",point={0,-2.55},role="code",fill="result",id="surface:result"}}
ledger:fade_in(items[1],{duration=0.25,curve="gentle"});ledger:fade_in(items[2],{duration=0.30,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(ledger,cloudReady);ledger:fade_in(items[3],{duration=0.26,curve="gentle"});waitUntil(ledger,normalReady-0.55);ledger:fade_in(items[4],{duration=0.30,curve="gentle"});ledger:fade_in(items[5],{duration=0.26,curve="gentle"});waitUntil(ledger,surfaceReady-0.36);ledger:fade_in(items[6],{duration=0.28,curve="gentle"});ledger:fade_in(items[7],{duration=0.30,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="Organized point cloud → normals → surface",point={0,2.65},role="h2",fill="foreground",id="surface:title"};local subtitle=page:text {text="stable grid adjacency turns samples into tangents, normals, and triangles",point={0,2.25},role="text",fill="muted",id="surface:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
