-- Reference study: compare a unit-quaternion great-circle interpolation with
-- a two-leg Euler route between the same 3D directions.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local function dot(a,b)return a[1]*b[1]+a[2]*b[2]+a[3]*b[3]end
local function scale(v,s)return{v[1]*s,v[2]*s,v[3]*s}end
local function add(a,b)return{a[1]+b[1],a[2]+b[2],a[3]+b[3]}end
local function normalize(v)local n=math.sqrt(dot(v,v));assert(n>1e-9,"zero vector");return scale(v,1/n)end
local a=normalize({1.0,0.18,0.12});local b=normalize({-0.42,0.78,0.46});local omega=math.acos(math.max(-1,math.min(1,dot(a,b))))
local function slerp(t)local s=math.sin(omega);return add(scale(a,math.sin((1-t)*omega)/s),scale(b,math.sin(t*omega)/s))end
local slerpPoints={};for i=0,64 do local p=slerp(i/64);assert(math.abs(dot(p,p)-1)<1e-8,"SLERP stays on unit sphere");slerpPoints[#slerpPoints+1]=p end
local mid=normalize({b[1],a[2],b[3]});local eulerPath={};for i=0,32 do local t=i/32;eulerPath[#eulerPath+1]=normalize(add(scale(a,1-t),scale(mid,t)))end;for i=1,32 do local t=i/32;eulerPath[#eulerPath+1]=normalize(add(scale(mid,1-t),scale(b,t)))end
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={4.4,3.2,5.6},target={0,0,0},up={0,1,0},projection="perspective",fov=0.58,near=0.1,far=20}}
local space=spatial:space {x={-1.8,1.8,0.5},y={-1.8,1.8,0.5},z={-1.8,1.8,0.5},opacity=0.14,id="slerp:space"}
local guide={};for ring=0,2 do local pts={};for i=0,64 do local t=2*math.pi*i/64;if ring==0 then pts[#pts+1]={math.cos(t),math.sin(t),0}elseif ring==1 then pts[#pts+1]={math.cos(t),0,math.sin(t)}else pts[#pts+1]={0,math.cos(t),math.sin(t)}end end;guide[#guide+1]=space:plot {points=pts,color="border",width=1.2,id="slerp:ring:"..ring}end
local va=space:vector {origin={0,0,0},value=a,color="accent",width=4,tip=13,layer=10,id="slerp:a"};local vb=space:vector {origin={0,0,0},value=b,color="result",width=4,tip=13,layer=10,id="slerp:b"}
local labels={space:text {text="q₀",point=scale(a,1.22),role="code",fill="accent",layer=20,id="slerp:a-label"},space:text {text="q₁",point=scale(b,1.22),role="code",fill="result",layer=20,id="slerp:b-label"}}
local euler=space:plot {points=eulerPath,color="muted",width=2,dash={7,5},id="slerp:euler-path"};local arc=space:plot {points=slerpPoints,color="warning",width=4,id="slerp:great-circle"};local halfway=slerp(0.5);local halfVector=space:vector {origin={0,0,0},value=halfway,color="warning",width=4,tip=13,layer=12,id="slerp:half"};local halfLabel=space:text {text="q(0.5)",point=scale(halfway,1.24),role="code",fill="warning",layer=20,id="slerp:half-label"}
spatial:create(space,0.28,"ease_out");spatial:create(guide,0.48,"ease_out",0.04);spatial:create({va,vb},0.50,"ease_out",0.08);for _,v in ipairs(labels)do spatial:fade_in(v,{duration=0.16,curve="gentle"})end;spatial:wait(0.44);spatial:create(euler,0.72,"ease_out");local eulerReady=spatial:duration();spatial:create(arc,1.05,"linear");spatial:create(halfVector,0.40,"ease_out");spatial:fade_in(halfLabel,{duration=0.20,curve="gentle"});local arcReady=spatial:duration();spatial:wait(2.0);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local items={ledger:text {text="ROTATION PATHS",point={0,3.05},role="h3",fill="foreground",id="slerp:ledger-title"},ledger:text {text="Euler route\naxis order chooses a waypoint",point={-2.72,2.10},align={0,0.5},role="code",fill="muted",id="slerp:euler-copy"},ledger:text {text="SLERP",point={-2.72,0.92},align={0,0.5},role="h3",fill="warning",id="slerp:slerp-title"},ledger:text {text="q(t) = sin((1−t)Ω)/sinΩ · q₀\n     + sin(tΩ)/sinΩ · q₁",point={-2.72,0.08},align={0,0.5},role="code",size=10.5,fill="foreground",id="slerp:formula"},ledger:text {text=string.format("Ω = %.1f°",math.deg(omega)),point={-2.72,-0.92},align={0,0.5},role="code",fill="result",id="slerp:angle"},ledger:text {text="invariant: ‖q(t)‖ = 1\nshortest great-circle arc",point={0,-2.15},role="code",fill="result",id="slerp:invariant"}}
ledger:fade_in(items[1],{duration=0.25,curve="gentle"});ledger:fade_in(items[2],{duration=0.34,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(ledger,eulerReady);ledger:fade_in(items[3],{duration=0.24,curve="gentle"});ledger:fade_in(items[4],{duration=0.34,curve="gentle"});waitUntil(ledger,arcReady-0.45);ledger:fade_in(items[5],{duration=0.24,curve="gentle"});ledger:fade_in(items[6],{duration=0.30,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="Quaternion SLERP · shortest 3D rotation",point={0,2.65},role="h2",fill="foreground",id="slerp:title"};local subtitle=page:text {text="unit orientation stays on a great circle while an Euler route depends on axis order",point={0,2.25},role="text",fill="muted",id="slerp:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
