-- Reference study: one world-space receiver is projected into a light view,
-- where its depth is compared with the blocker depth already stored at a texel.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local function add(a,b)return{a[1]+b[1],a[2]+b[2],a[3]+b[3]}end
local function sub(a,b)return{a[1]-b[1],a[2]-b[2],a[3]-b[3]}end
local function scale(v,s)return{v[1]*s,v[2]*s,v[3]*s}end
local function dot(a,b)return a[1]*b[1]+a[2]*b[2]+a[3]*b[3]end
local function cross(a,b)return{a[2]*b[3]-a[3]*b[2],a[3]*b[1]-a[1]*b[3],a[1]*b[2]-a[2]*b[1]}end
local function normalize(v)local n=math.sqrt(dot(v,v));assert(n>1e-9,"zero vector");return scale(v,1/n)end
local light={2.55,3.55,1.75};local receiver={-0.72,-0.72,-0.38};local lightToReceiver=sub(receiver,light);local receiverDistance=math.sqrt(dot(lightToReceiver,lightToReceiver));local direction=normalize(lightToReceiver)
local blockerCenter=add(light,scale(direction,receiverDistance*0.54));local helper={0,1,0};local side=normalize(cross(direction,helper));local up=normalize(cross(side,direction));local blockerDistance=receiverDistance*0.54;local bias=0.025;local shadowed=blockerDistance<receiverDistance-bias
assert(shadowed,"fixture must be shadowed")
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={5.8,3.8,6.8},target={0,0.55,0},up={0,1,0},projection="perspective",fov=0.64,near=0.1,far=30}}
local space=spatial:space {x={-3,3.5,1},y={-1.4,4.2,1},z={-3,3,1},opacity=0.12,id="shadowmap:space"}
local ground=space:polygon {points={{-2.7,-0.72,-2.4},{2.7,-0.72,-2.4},{2.7,-0.72,2.4},{-2.7,-0.72,2.4}},fill="#4fc1ff16",stroke="border",width=1.4,id="shadowmap:receiver"}
local blocker=space:polygon {points={add(add(blockerCenter,scale(side,-0.72)),scale(up,-0.62)),add(add(blockerCenter,scale(side,0.72)),scale(up,-0.62)),add(add(blockerCenter,scale(side,0.72)),scale(up,0.62)),add(add(blockerCenter,scale(side,-0.72)),scale(up,0.62))},fill="#8b5cf660",stroke="focus",width=2,id="shadowmap:blocker"}
local lightPoint=space:point {point=light,radius=10,fill="warning",stroke="background",width=1.5,layer=10,id="shadowmap:light"};local lightLabel=space:text {text="light camera",point=add(light,{0.30,-0.34,0}),align={0,0.5},role="code",fill="warning",layer=20,id="shadowmap:light-label"}
local receiverPoint=space:point {point=receiver,radius=9,fill="result",stroke="background",width=1.4,layer=10,id="shadowmap:sample"};local receiverLabel=space:text {text="receiver p",point=add(receiver,{0.10,0.28,0}),align={0,0.5},role="code",fill="result",layer=20,id="shadowmap:sample-label"}
local lightPath=space:line {from=light,to=receiver,color="warning",width=3.5,dash={9,6},layer=8,id="shadowmap:light-path"};local blockerPoint=space:point {point=blockerCenter,radius=7,fill="focus",layer=11,id="shadowmap:stored-hit"}
spatial:create(space,0.28,"ease_out");spatial:draw_border_then_fill(ground,0.48,"ease_out");spatial:create(lightPoint,0.24,"ease_out");spatial:fade_in(lightLabel,{duration=0.20,curve="gentle"});spatial:draw_border_then_fill(blocker,0.48,"ease_out");spatial:create(receiverPoint,0.22,"ease_out");spatial:fade_in(receiverLabel,{duration=0.20,curve="gentle"});spatial:wait(0.45);spatial:create(lightPath,0.72,"linear");spatial:create(blockerPoint,0.22,"ease_out");local compareReady=spatial:duration();spatial:indicate(blocker,{scale=1.03,duration=0.36,curve="gentle"});spatial:wait(2.0);local spatialEnd=spatial:duration()
local map=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local texel=map:rectangle {center={0,1.62},size={4.2,2.20},fill="#8b5cf62c",stroke="border",width=1.5,id="shadowmap:texel"};local storedBar=map:rectangle {center={-0.72,1.35},size={0.62,1.05},fill="focus",stroke="focus",id="shadowmap:stored-bar"};local receiverBar=map:rectangle {center={0.72,1.08},size={0.62,1.58},fill="result",stroke="result",id="shadowmap:receiver-bar"}
local items={map:text {text="LIGHT DEPTH TEXEL",point={0,3.16},role="h3",fill="foreground",id="shadowmap:title-map"},map:text {text=string.format("stored = %.3f",blockerDistance),point={-0.72,0.28},role="code",size=10.5,fill="focus",id="shadowmap:stored-value"},map:text {text=string.format("receiver = %.3f",receiverDistance),point={0.72,-0.12},role="code",size=10.5,fill="result",id="shadowmap:receiver-value"},map:text {text="project p with light VP\n→ sample stored depth\n→ compare receiver depth",point={0,-1.35},role="code",fill="foreground",id="shadowmap:steps"},map:text {text=string.format("%.3f < %.3f − %.3f",blockerDistance,receiverDistance,bias),point={0,-2.32},role="code",fill="warning",id="shadowmap:comparison"},map:text {text="visibility = 0 · shadowed",point={0,-2.90},role="code",fill="danger",id="shadowmap:result"}}
map:create(texel,0.34,"ease_out");map:fade_in(items[1],{duration=0.24,curve="gentle"});map:grow_from_edge(storedBar,"bottom",0.42,"ease_out");map:fade_in(items[2],{duration=0.22,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(map,compareReady-0.70);map:grow_from_edge(receiverBar,"bottom",0.52,"ease_out");for i=3,6 do map:fade_in(items[i],{duration=0.25,curve="gentle"})end;waitUntil(map,spatialEnd)
local title=page:text {text="Shadow mapping · compare in the light's view",point={0,2.65},role="h2",fill="foreground",id="shadowmap:page-title"};local subtitle=page:text {text="the depth map stores the nearest light-space surface, not a dark color",point={0,2.25},role="text",fill="muted",id="shadowmap:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(map,{x=0.638,y=0.23,width=0.336,height=0.72});return page
