-- Reference study: one Catmull-Clark iteration on a closed cube. Face, edge,
-- and vertex points are derived from the same topology before 24 quads form.
local page=tmath.scene {width=960,height=540,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=6}}
local function add(a,b)return{a[1]+b[1],a[2]+b[2],a[3]+b[3]}end
local function scale(v,s)return{v[1]*s,v[2]*s,v[3]*s}end
local vertices={{-1,-1,-1},{1,-1,-1},{1,1,-1},{-1,1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}}
local faces={{1,4,3,2},{5,6,7,8},{1,2,6,5},{4,8,7,3},{2,3,7,6},{1,5,8,4}}
local edges,faceEdges={},{}
local function edgeFor(a,b,faceIndex)
 for i,e in ipairs(edges)do if(e.a==a and e.b==b)or(e.a==b and e.b==a)then e.faces[#e.faces+1]=faceIndex;return i end end
 edges[#edges+1]={a=a,b=b,faces={faceIndex}};return#edges
end
for fi,f in ipairs(faces)do faceEdges[fi]={};for i=1,#f do faceEdges[fi][i]=edgeFor(f[i],f[i%#f+1],fi)end end
local facePoints={};for fi,f in ipairs(faces)do local sum={0,0,0};for _,vi in ipairs(f)do sum=add(sum,vertices[vi])end;facePoints[fi]=scale(sum,1/#f)end
local edgePoints={};for i,e in ipairs(edges)do assert(#e.faces==2,"closed cube edge must have two faces");edgePoints[i]=scale(add(add(vertices[e.a],vertices[e.b]),add(facePoints[e.faces[1]],facePoints[e.faces[2]])),0.25)end
local vertexFaces,vertexEdges={},{};for i=1,#vertices do vertexFaces[i]={};vertexEdges[i]={}end;for fi,f in ipairs(faces)do for _,vi in ipairs(f)do vertexFaces[vi][#vertexFaces[vi]+1]=fi end end;for ei,e in ipairs(edges)do vertexEdges[e.a][#vertexEdges[e.a]+1]=ei;vertexEdges[e.b][#vertexEdges[e.b]+1]=ei end
local vertexPoints={};for vi,p in ipairs(vertices)do local F={0,0,0};for _,fi in ipairs(vertexFaces[vi])do F=add(F,facePoints[fi])end;local n=#vertexFaces[vi];F=scale(F,1/n);local R={0,0,0};for _,ei in ipairs(vertexEdges[vi])do local e=edges[ei];R=add(R,scale(add(vertices[e.a],vertices[e.b]),0.5))end;R=scale(R,1/#vertexEdges[vi]);vertexPoints[vi]=scale(add(add(F,scale(R,2)),scale(p,n-3)),1/n)end
local quads={};for fi,f in ipairs(faces)do for i,vi in ipairs(f)do local prev=i==1 and #f or i-1;quads[#quads+1]={vertexPoints[vi],edgePoints[faceEdges[fi][i]],facePoints[fi],edgePoints[faceEdges[fi][prev]]}end end
assert(#vertices+#edges+#faces==26 and #quads==24 and 26-48+24==2,"one closed subdivision must preserve Euler characteristic")
local spatial=tmath.scene {width=620,height=410,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="3d",eye={4.8,3.8,6.1},target={0,0,0},up={0,1,0},projection="perspective",fov=0.58,near=0.1,far=25}}
local space=spatial:space {x={-2.2,2.2,1},y={-2.2,2.2,1},z={-2.2,2.2,1},opacity=0.13,id="subdiv:space"};local coarse=space:group {id="subdiv:coarse"};local coarseFaces={};for i,f in ipairs(faces)do local pts={};for _,vi in ipairs(f)do pts[#pts+1]=vertices[vi]end;coarseFaces[i]=coarse:polygon {points=pts,fill=i%2==0 and "#4fc1ff30" or "#8b5cf630",stroke="accent",width=2,id="subdiv:coarse-face:"..i}end
local faceMarks={};for i,p in ipairs(facePoints)do faceMarks[i]=space:point {point=p,radius=7,fill="warning",layer=10,id="subdiv:face-point:"..i}end;local edgeMarks={};for i,p in ipairs(edgePoints)do edgeMarks[i]=space:point {point=p,radius=5.5,fill="focus",layer=10,id="subdiv:edge-point:"..i}end;local vertexMarks={};for i,p in ipairs(vertexPoints)do vertexMarks[i]=space:point {point=p,radius=5.5,fill="accent",layer=10,id="subdiv:vertex-point:"..i}end
local refined=space:group {id="subdiv:refined"};local refinedFaces={};for i,q in ipairs(quads)do refinedFaces[i]=refined:polygon {points=q,fill=i%3==0 and "#8b5cf64a" or "#4fc1ff3b",stroke="result",width=1,id="subdiv:quad:"..i}end
spatial:create(space,0.28,"ease_out");spatial:draw_border_then_fill(coarseFaces,0.64,"ease_out",0.035);spatial:wait(0.45);spatial:create(faceMarks,0.34,"ease_out",0.05);local faceReady=spatial:duration();spatial:create(edgeMarks,0.46,"ease_out",0.025);local edgeReady=spatial:duration();spatial:create(vertexMarks,0.40,"ease_out",0.035);local vertexReady=spatial:duration();spatial:fade(coarse,0.12,0.36,"gentle");spatial:draw_border_then_fill(refinedFaces,0.92,"ease_out",0.012);local refinedReady=spatial:duration();spatial:indicate(refined,{scale=1.02,duration=0.36,curve="gentle"});spatial:wait(2.0);local spatialEnd=spatial:duration()
local ledger=tmath.scene {width=336,height=405,fps=30,loop=false,theme="adaptive_vscode",camera={mode="fixed",view="2d",target={0,0},height=7.4}}
local items={ledger:text {text="CATMULL–CLARK",point={0,3.02},role="h3",fill="foreground",id="subdiv:ledger-title"},ledger:text {text="6 face points\nF = average(face vertices)",point={-2.70,2.10},align={0,0.5},role="code",fill="warning",id="subdiv:face-rule"},ledger:text {text="12 edge points\nE = (P0 + P1 + F0 + F1) / 4",point={-2.70,0.80},align={0,0.5},role="code",size=10.5,fill="focus",id="subdiv:edge-rule"},ledger:text {text="8 vertex points\nV' = (F + 2R + (n−3)V) / n",point={-2.70,-0.55},align={0,0.5},role="code",size=10.5,fill="accent",id="subdiv:vertex-rule"},ledger:text {text="26 vertices · 48 edges · 24 quads",point={0,-1.80},role="code",fill="result",id="subdiv:counts"},ledger:text {text="V − E + F = 2",point={0,-2.55},role="h3",fill="result",id="subdiv:euler"}}
ledger:fade_in(items[1],{duration=0.25,curve="gentle"});local function waitUntil(scene,t)local d=t-scene:duration();if d>0 then scene:wait(d)end end;waitUntil(ledger,faceReady-0.30);ledger:fade_in(items[2],{duration=0.30,curve="gentle"});waitUntil(ledger,edgeReady-0.30);ledger:fade_in(items[3],{duration=0.30,curve="gentle"});waitUntil(ledger,vertexReady-0.30);ledger:fade_in(items[4],{duration=0.30,curve="gentle"});waitUntil(ledger,refinedReady-0.45);ledger:fade_in(items[5],{duration=0.28,curve="gentle"});ledger:fade_in(items[6],{duration=0.30,curve="gentle"});waitUntil(ledger,spatialEnd)
local title=page:text {text="Catmull–Clark subdivision · one cube iteration",point={0,2.65},role="h2",fill="foreground",id="subdiv:title"};local subtitle=page:text {text="face, edge, and vertex rules rebuild one closed cube as 24 quads",point={0,2.25},role="text",fill="muted",id="subdiv:subtitle"};page:fade_in(title,{shift={0,-0.08},duration=0.38,curve="gentle"});page:fade_in(subtitle,{duration=0.28,curve="gentle"});page:viewport(spatial,{x=0.015,y=0.23,width=0.613,height=0.72});page:viewport(ledger,{x=0.638,y=0.23,width=0.336,height=0.72});return page
