const api = (group, name, signature, lua, summary, returns = "") => ({
    group,
    name,
    signature,
    lua,
    summary,
    returns,
});

export const API = [
    api(
        "Runtime",
        "createTMath",
        "createTMath(source: string | SceneBuilder, name?: string, moduleOptions?: Record<string, unknown>): Promise<TMathScene>",
        "—",
        "Create one WASM engine and load Lua or a typed JavaScript scene.",
        "Promise<TMathScene>",
    ),
    api(
        "Runtime",
        "evaluateScene",
        "evaluateScene(source: string, name?: string): SceneBuilder",
        "—",
        "Evaluate trusted JavaScript editor code with the tmath facade.",
        "SceneBuilder",
    ),
    api(
        "Runtime",
        "compileScene",
        "compileScene(scene: SceneBuilder): string",
        "—",
        "Serialize a JavaScript scene definition to the bounded Lua DSL.",
        "string",
    ),
    api(
        "Runtime",
        "TMathScene.load",
        "scene.load(source: string | SceneBuilder, name?: string): number",
        "—",
        "Hot-load either language while preserving the last valid scene on failure.",
        "duration in seconds",
    ),
    api(
        "Runtime",
        "TMathScene.loadLua",
        "scene.loadLua(source: string, name?: string): number",
        "—",
        "Hot-load a Lua scene into the current engine.",
        "duration in seconds",
    ),
    api(
        "Runtime",
        "TMathScene.loadScene",
        "scene.loadScene(definition: SceneBuilder, name?: string): number",
        "—",
        "Compile and hot-load a JavaScript scene definition.",
        "duration in seconds",
    ),
    api(
        "Runtime",
        "TMathScene.loop",
        "readonly scene.loop: boolean",
        "—",
        "Read the root Scene playback policy. false is the default and stops the Playground on the final frame.",
        "boolean",
    ),
    api(
        "Runtime",
        "TMathScene.render",
        "scene.render(time: number, copy?: boolean): Uint8ClampedArray",
        "—",
        "Render an SW offscreen RGBA frame. The zero-copy view is transient.",
        "RGBA byte view",
    ),
    api(
        "Runtime",
        "TMathScene.lottie",
        "scene.lottie(fps?: number): Uint8Array",
        "—",
        "Serialize the current scene to a stable copy of ThorVG-compatible Lottie JSON bytes.",
        "Lottie JSON byte array",
    ),
    api(
        "Runtime",
        "TMathScene.bounds",
        "scene.bounds(object: string, time?: number): BBox",
        "—",
        "Measure the visible tagged object family through ThorVG in scene-pixel coordinates, including glyphs, strokes, and camera projection.",
        "BBox",
    ),
    api(
        "Runtime",
        "TMathScene.intersects",
        "scene.intersects(first: string, second: string, time?: number, padding?: number): boolean",
        "—",
        "Test two tagged render bounds. Positive padding enforces extra pixel clearance; edge contact alone is not an overlap.",
        "boolean",
    ),
    api(
        "Runtime",
        "TMathScene.layoutReport",
        "scene.layoutReport(time?: number, padding?: number): LayoutReport",
        "—",
        "Measure the complete root and nested-Viewport composition in root pixels, including own/family bounds, clipping, stretch, collisions, and ancestor-content containment.",
        "LayoutReport",
    ),
    api(
        "Runtime",
        "TMathScene.draw",
        "scene.draw(canvas: HTMLCanvasElement, time: number, pixelRatio?: number): void",
        "—",
        "Render one frame to a browser Canvas 2D target, optionally at a higher pixel density.",
    ),
    api(
        "Runtime",
        "TMathScene.camera",
        "scene.camera(action: CameraAction, x?: number, y?: number): boolean",
        "—",
        "Apply the same normalized camera command used by native hosts. Fixed mode returns false.",
        "boolean",
    ),
    api(
        "Runtime",
        "TMathScene.cameraMode",
        'readonly scene.cameraMode: "fixed" | "interactive"',
        "—",
        "Read whether external camera input is accepted.",
        "string",
    ),
    api(
        "Runtime",
        "TMathScene.cameraView",
        'readonly scene.cameraView: "2d" | "3d"',
        "—",
        "Read the active planar or spatial view.",
        "string",
    ),
    api(
        "Runtime",
        "TMathScene.font",
        "scene.font(name: string, data: Uint8Array | ArrayBuffer, mime?: string): void",
        "—",
        "Register in-memory font bytes for WASM text rendering.",
    ),
    api(
        "Runtime",
        "TMathScene.asset",
        "scene.asset(name: string, data: Uint8Array | ArrayBuffer, mime: string): void",
        "—",
        "Decode and register PNG, JPG, WebP, or SVG bytes through the ThorVG Asset Loader before loading a scene.",
    ),
    api(
        "Runtime",
        "TMathScene.size",
        "scene.size(): [number, number]",
        "—",
        "Read the render surface dimensions.",
        "[width, height]",
    ),
    api(
        "Runtime",
        "TMathScene.resize",
        "scene.resize(width: number, height: number): void",
        "—",
        "Resize within the 67,108,864-pixel safety limit.",
    ),
    api(
        "Runtime",
        "TMathScene.destroy",
        "scene.destroy(): void",
        "—",
        "Release the WASM engine. Repeated calls are safe.",
    ),

    api(
        "Scene",
        "tmath.scene",
        "tmath.scene(config?: SceneConfig): SceneBuilder",
        "tmath.scene(config) -> scene",
        "Create a global scene that can own root Object trees and isolated child Viewports.",
        "SceneBuilder",
    ),
    api(
        "Scene",
        "SceneBuilder.viewport",
        "scene.viewport(child: SceneBuilder, bounds: ViewportBounds): this",
        "scene:viewport(child, bounds)",
        "Seal and transfer an independently authored child Scene into a normalized clipped rectangle.",
        "SceneBuilder",
    ),
    api(
        "Scene",
        "SceneBuilder.sceneTransition",
        "scene.sceneTransition(stages: readonly SceneBuilder[], options?: SceneTransitionOptions): this",
        "scene:scene_transition(stages, options)",
        "Seal independent stage Scenes and morph equal-ID objects between their final frames; unmatched content cross-fades.",
        "SceneBuilder",
    ),
    api(
        "Composition",
        "ObjectFactory.group",
        "receiver.group(options?: GroupOptions): GroupHandle",
        "receiver:group(options) -> group",
        "Create a paintless semantic container. A Scene receiver creates a root; an ObjectHandle receiver creates a child.",
        "GroupHandle",
    ),
    api(
        "Composition",
        "ObjectFactory.space",
        "receiver.space(options?: SpaceOptions): SpaceHandle",
        "receiver:space(options) -> space",
        "Create a matrix coordinate space as a root or child. All ancestor matrices compose.",
        "SpaceHandle",
    ),
    api(
        "Composition",
        "SpaceHandle.cell",
        "space.cell(callback: CellSampler, options?: CellSampleOptions): GroupHandle",
        "space:cell(function(x, y, time) return color end, options) -> group",
        "Precompute a bounded Space X/Y/time field during authoring. Positive duration/fps options retain interpolated frames and consume that Scene interval.",
        "GroupHandle",
    ),
    api(
        "Composition",
        "SpaceHandle.voxel",
        "space.voxel(callback: VoxelSampler, options?: VoxelSampleOptions): GroupHandle",
        "space:voxel(function(x, y, z, time) return color end, options) -> group",
        "Precompute a bounded Space X/Y/Z/time field during authoring and create retained z-sliced voxel Cells. Rendering never invokes the callback.",
        "GroupHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.point",
        "receiver.point(options: PointOptions): ObjectHandle",
        "receiver:point(options) -> handle",
        "Create a screen-sized marker at a receiver-local coordinate.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.line",
        "receiver.line(options: LineOptions): ObjectHandle",
        "receiver:line(options) -> handle",
        "Create a segment in receiver-local coordinates.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.arrow",
        "receiver.arrow(options: ArrowOptions): ObjectHandle",
        "receiver:arrow(options) -> handle",
        "Create a directed segment with independent pixel-sized tail and tip caps.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.vector",
        "receiver.vector(options: VectorOptions): ObjectHandle",
        "receiver:vector(options) -> handle",
        "Display a mathematical vector in receiver-local coordinates.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.circle",
        "receiver.circle(options?: CircleOptions): ObjectHandle",
        "receiver:circle(options) -> handle",
        "Create a circle in the receiver's local XY plane.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.rectangle",
        "receiver.rectangle(options?: RectangleOptions): ObjectHandle",
        "receiver:rectangle(options) -> handle",
        "Create an axis-aligned rectangle with an optional rounded corner radius.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.polygon",
        "receiver.polygon(options: PolygonOptions): ObjectHandle",
        "receiver:polygon(options) -> handle",
        "Create a closed polygon from at least three receiver-local points.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.plot",
        "receiver.plot(options: PlotOptions): ObjectHandle",
        "receiver:plot({points = ...}) -> handle",
        "Create a sampled local graph. Lua additionally accepts fn with x_range.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.route",
        "receiver.route(options: RouteOptions): ObjectHandle",
        "receiver:route({points = ..., dash = ..., tip = ...}) -> handle",
        "Create one directed polyline whose dashed shaft and solid endpoint markers share one timeline state.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.path",
        "receiver.path(options: PathOptions): ObjectHandle",
        "receiver:path(options) -> handle",
        "Create one open or closed contour from move, line, quadratic, cubic, and final close commands.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.curve",
        "receiver.curve(options: CurveOptions): ObjectHandle",
        "receiver:curve(options) -> handle",
        "Create a cubic Bézier curve from two endpoints and two control points.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.surface",
        "receiver.surface(options: SurfaceOptions): ObjectHandle",
        "receiver:surface(options) -> handle",
        "Create a sampled 3D surface. Solid mode hides cell seams; shading=false keeps its authored fill uniform.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.text",
        "receiver.text(options: TextOptions): ObjectHandle",
        "receiver:text(options) -> handle",
        "Create billboard text, or plane-oriented world-space text with orientation set to plane.",
        "ObjectHandle",
    ),
    api(
        "Composition",
        "ObjectHandle.label",
        "handle.label(options: TextOptions): ObjectHandle",
        "handle:label(options) -> handle",
        "Create an ordinary child Text as one Object's semantic label. Placement and styling remain explicit, and the returned handle is a normal Text Object.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.ruler",
        "receiver.ruler(options: RulerOptions): ObjectHandle",
        "receiver:ruler(options) -> handle",
        "Create a local ruler with pixel-sized ticks.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.svg",
        "receiver.svg(options: SvgOptions): ObjectHandle",
        "receiver:svg(options) -> handle",
        "Load trusted file-backed SVG on native builds; unavailable in filesystem-free WASM.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.image",
        "receiver.image(options: ImageOptions): ObjectHandle",
        "receiver:image(options) -> handle",
        "Place a decoded Asset or inline row-major pixel buffer in receiver-local coordinates while preserving its source aspect ratio.",
        "ObjectHandle",
    ),
    api(
        "Objects",
        "ObjectFactory.cell",
        "receiver.cell(options: CellOptions): ObjectHandle",
        "receiver:cell(options) -> handle",
        "Create one batched cell region, optionally texture and patch it; spatial view lowers cells to shaded voxels.",
        "ObjectHandle",
    ),
    api(
        "Composition",
        "ObjectFactory.connector",
        "receiver.connector(from: ObjectHandle, to: ObjectHandle, options?: ConnectorOptions): ObjectHandle",
        "receiver:connector({from = from, to = to, ...options}) -> handle",
        "Create sampled derived geometry between two same-Scene object bounds. It follows animated endpoints without an updater callback; animate those endpoints instead of transforming the Connector.",
        "ObjectHandle",
    ),
    api(
        "Layout",
        "ObjectHandle.moveTo",
        "handle.moveTo(point: WorldVector): this",
        "handle:move_to(point)",
        "Move one object family so its geometry-bounds center reaches a parent-space point.",
        "ObjectHandle",
    ),
    api(
        "Layout",
        "ObjectHandle.nextTo",
        "handle.nextTo(target: ObjectHandle, direction: WorldVector, gap?: number): this",
        "handle:next_to(target, direction, gap)",
        "Place same-parent object families beside each other along a direction. The default gap is 0.25.",
        "ObjectHandle",
    ),
    api(
        "Layout",
        "ObjectHandle.alignTo",
        "handle.alignTo(target: ObjectHandle, direction: WorldVector): this",
        "handle:align_to(target, direction)",
        "Align selected bounds edges of two same-parent object families.",
        "ObjectHandle",
    ),
    api(
        "Layout",
        "GroupHandle.arrange",
        "group.arrange(direction?: WorldVector, gap?: number): this",
        "group:arrange(direction, gap)",
        "Lay out direct children along a direction, centered around the Group origin.",
        "GroupHandle",
    ),
    api(
        "Layout",
        "GroupHandle.arrangeGrid",
        "group.arrangeGrid(columns: number, columnGap?: number, rowGap?: number): this",
        "group:arrange_grid(columns, column_gap, row_gap)",
        "Lay out direct children in a centered row-major grid.",
        "GroupHandle",
    ),

    api(
        "Timeline",
        "SceneBuilder.create",
        "scene.create(target: Handle | readonly Handle[], duration?: number, curve?: AnimCurve, lag?: number, direction?: CreateDirection): this",
        "scene:create(handle_or_array, duration, curve, lag, direction)",
        "Reveal one object or a lagged group along its geometry. Forward circles begin at 3 o'clock and draw counterclockwise on screen; clockwise selects the reverse traversal.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.uncreate",
        "scene.uncreate(target: Handle | readonly Handle[], duration?: number, curve?: AnimCurve, lag?: number, direction?: CreateDirection): this",
        "scene:uncreate(handle_or_array, duration, curve, lag, direction)",
        "Erase geometry in the selected path direction while keeping its handle reusable.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.fillReveal",
        "scene.fillReveal(target: Handle | readonly Handle[], duration?: number, curve?: AnimCurve, lag?: number): this",
        "scene:fill_reveal(handle_or_array, duration, curve, lag)",
        "Reveal authored fill alpha while preserving the completed stroke; schedule after create for a separate fill beat.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.drawBorderThenFill",
        "scene.drawBorderThenFill(target: Handle | readonly Handle[], duration?: number, curve?: AnimCurve, lag?: number, direction?: CreateDirection): this",
        "scene:draw_border_then_fill(handle_or_array, duration, curve, lag, direction)",
        "Draw the boundary during the first two thirds of one clip, then reveal the fill during the final third.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.write",
        "scene.write(target: Handle | readonly Handle[], duration?: number, curve?: AnimCurve, lag?: number, direction?: CreateDirection): this",
        "scene:write(handle_or_array, duration, curve, lag, direction)",
        "Trace a contour while filling only its already traversed region. Fill-only paths receive a temporary same-color writing stroke.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.fadeIn",
        "scene.fadeIn(target: Handle, options?: FadeOptions): this",
        "scene:fade_in(handle, options)",
        "Introduce an object with opacity plus optional directional movement and scale.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.fadeOut",
        "scene.fadeOut(target: Handle, options?: FadeOptions): this",
        "scene:fade_out(handle, options)",
        "Hide an object with opacity plus optional directional movement and scale.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.growFromCenter",
        "scene.growFromCenter(target: Handle, duration?: number, curve?: AnimCurve): this",
        "scene:grow_from_center(handle, duration, curve)",
        "Introduce an object by growing its complete visual family from its center.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.shrinkToCenter",
        "scene.shrinkToCenter(target: Handle, duration?: number, curve?: AnimCurve): this",
        "scene:shrink_to_center(handle, duration, curve)",
        "Hide an object by shrinking its complete visual family to its center.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.indicate",
        "scene.indicate(target: Handle, options?: IndicateOptions): this",
        "scene:indicate(handle, options)",
        "Temporarily scale and recolor an object, then restore its exact prior state.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.morph",
        "scene.morph(source: Handle | Handle[], target: Handle | Handle[], duration?: number, curve?: AnimCurve, lag?: number): this",
        "scene:morph(source, target, duration, curve, lag)",
        "Morph one pair or equally sized arrays of same-parent childless Polygon, Plot, Path, or Curve geometry. Sampled Cell/Voxel Groups use their callback time argument instead. Each source is replaced by its target at the end boundary.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.replacementTransform",
        "scene.replacementTransform(source: Handle | Handle[], target: Handle | Handle[], duration?: number, curve?: AnimCurve, lag?: number): this",
        "scene:replacement_transform(source, target, duration, curve, lag)",
        "Explicit alias for replacement-style morphing. It accepts one pair or equally sized arrays; each source becomes dead and its target becomes active at the pair's end boundary.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.fadeTransform",
        "scene.fadeTransform(source: Handle, target: Handle, duration?: number, curve?: AnimCurve): this",
        "scene:fade_transform(source, target, duration, curve)",
        "Cross-fade between unrelated object families, consume the source at the end, and continue with the newly attached target handle.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.shift",
        "scene.shift(target: Handle, by: WorldVector, duration?: number, curve?: AnimCurve): this",
        "scene:shift(handle, vector, duration, curve)",
        "Compose a relative translation in the parent space. Connector targets and edge-only Connector ancestors are rejected; move an endpoint or a node-owning ancestor instead.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.transform",
        "scene.transform(target: Handle, matrix: Mat4, duration?: number, curve?: AnimCurve): this",
        "scene:transform(handle, mat4, duration, curve)",
        "Animate an object's local-to-parent matrix. Transforming a Space moves its full subtree; Connector-derived geometry requires the target subtree to own at least one endpoint.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.fade",
        "scene.fade(target: Handle, opacity: number, duration?: number, curve?: AnimCurve): this",
        "scene:fade(handle, opacity, duration, curve)",
        "Animate opacity between zero and one.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.transition",
        "scene.transition(from: Handle | readonly Handle[], to: Handle | readonly Handle[], duration?: number, curve?: AnimCurve): this",
        "scene:transition(from, to, duration, curve)",
        "Cross-fade object groups in one timeline slot.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.stroke",
        "scene.stroke(target: Handle, color: Color, duration?: number, curve?: AnimCurve): this",
        "scene:stroke(handle, color, duration, curve)",
        "Animate stroke color.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.fill",
        "scene.fill(target: Handle, color: Color, duration?: number, curve?: AnimCurve): this",
        "scene:fill(handle, color, duration, curve)",
        "Animate fill color.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.play",
        "scene.play(specification: AnimationSpec | readonly AnimationSpec[], duration?: number, curve?: AnimCurve, lag?: number): this",
        "scene:play(descriptor_or_array, duration, curve, lag)",
        "Atomically animate one or more distinct same-Scene targets. Each descriptor can combine model, opacity, stroke, and fill changes in one clip.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.look",
        "scene.look(camera: CameraTarget, duration?: number, curve?: AnimCurve): this",
        "scene:look(camera, duration, curve)",
        "Animate a fixed camera with shortest-arc orientation interpolation. Paths with unsafe eye range, orbit precision, or near/far float separation are rejected atomically.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.wait",
        "scene.wait(duration?: number): this",
        "scene:wait(duration)",
        "Advance the scene timeline.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.remove",
        "scene.remove(target: Handle): this",
        "scene:remove(handle)",
        "Remove an object at the current timeline time.",
        "SceneBuilder",
    ),
    api(
        "Timeline",
        "SceneBuilder.compile",
        "scene.compile(): string",
        "—",
        "Compile the builder into the deterministic Lua DSL.",
        "string",
    ),

    api(
        "Types",
        "SceneConfig",
        "interface SceneConfig { width?: number; height?: number; fps?: number; background?: Color; theme?: ThemePreset | ThemeOptions; camera?: Camera; antialiasing?: boolean; loop?: boolean; }",
        "table",
        "Top-level resolution, timing, Scene-scoped Theme, optional background override, camera, ThorVG edge antialiasing, and playback-loop policy. loop defaults to false.",
    ),
    api(
        "Types",
        "ThemeColorRole",
        'type ThemeColorRole = "background" | "foreground" | "muted" | "accent" | "secondary" | "success" | "warning" | "danger" | "info" | "surface" | "border" | "result" | "focus"',
        "string",
        "Semantic Theme color names accepted by object paint, axes, Cells, gradients, color animations, and indicate effects.",
    ),
    api(
        "Types",
        "ThemePreset",
        'type ThemePreset = "3_blue_1_eyes" | "pro_white" | "pro_black" | "adaptive_vscode" | "pro"',
        '"3_blue_1_eyes" | "pro_white" | "pro_black" | "adaptive_vscode" | "pro"',
        "Built-in original dark lesson, light professional default, dark professional, and host-resolved VS Code Scene Themes. adaptive_vscode falls back to pro_white without a host palette; pro remains a compatibility alias for pro_white.",
    ),
    api(
        "Types",
        "TextTheme",
        "interface TextTheme { font?: string; size?: number; color?: Color; }",
        "{font?, size?, color?}",
        "Partial typography override for one semantic text role.",
    ),
    api(
        "Types",
        "AxisTheme",
        "interface AxisTheme { x?: Color; y?: Color; z?: Color; grid?: Color; label?: Color; }",
        "{x?, y?, z?, grid?, label?}",
        "Partial Space axis, grid, and number-label color override.",
    ),
    api(
        "Types",
        "SemanticTheme",
        "interface SemanticTheme { foreground?: Color; muted?: Color; accent?: Color; secondary?: Color; success?: Color; warning?: Color; danger?: Color; info?: Color; surface?: Color; border?: Color; result?: Color; focus?: Color; }",
        "table",
        "Reusable meaning-based colors. Use result for returned or derived output and focus for transient salience; indicate defaults to focus. Semantic role strings resolve from this table when the Scene is authored.",
    ),
    api(
        "Types",
        "ThemeOptions",
        "interface ThemeOptions { preset?: ThemePreset; background?: Color; text?: { h1?: TextTheme; h2?: TextTheme; h3?: TextTheme; text?: TextTheme; code?: TextTheme; }; objects?: readonly Color[]; object_width?: number; gradient?: boolean; end_gradient_stop?: Color; axis?: AxisTheme; colors?: SemanticTheme; }",
        "table",
        "Scene-scoped visual defaults. Objects replaces the shared 1..10-color cycle used in order by lhs, rhs, and every later args member; object_width supplies omitted shape stroke widths. When gradient is enabled, each resolved object color blends toward end_gradient_stop.",
    ),
    api(
        "Types",
        "ViewportBounds",
        "interface ViewportBounds { x: number; y: number; width: number; height: number; }",
        "table",
        "Normalized top-left child Scene bounds contained in [0,1].",
    ),
    api(
        "Types",
        "BBox",
        "interface BBox { readonly x: number; readonly y: number; readonly width: number; readonly height: number; }",
        "TMathBBox",
        "ThorVG render-space axis-aligned bounds in top-left scene pixels.",
    ),
    api(
        "Types",
        "SceneTransitionOptions",
        "type SceneTransitionOptions = { duration?: number; hold?: number; viewport?: ViewportBounds; easing?: AnimCurve; curve?: AnimCurve; }",
        "table",
        "Per-boundary morph duration, per-stage hold, destination rectangle, and timing curve. Use either easing or curve.",
    ),
    api(
        "Types",
        "Camera",
        'interface Camera { mode?: "fixed" | "interactive"; view?: "2d" | "3d"; target?: WorldVector; eye?: WorldVector; up?: WorldVector; height?: number; projection?: "perspective" | "orthographic"; fov?: number; near?: number; far?: number; }',
        "{mode, view, ...}",
        "Fixed cameras ignore external commands; interactive cameras accept pan, orbit, zoom, reset, and view switches.",
    ),
    api(
        "Types",
        "CameraTarget",
        'interface CameraTarget { view?: "2d" | "3d"; eye?: WorldVector; target?: WorldVector; up?: WorldVector; height?: number; projection?: "perspective" | "orthographic"; fov?: number; near?: number; far?: number; }',
        "table",
        "A code-defined fixed-camera keyframe, including planar/spatial projection changes.",
    ),
    api(
        "Types",
        "ObjectFactory",
        "interface ObjectFactory { group(...); space(...); point(...); line(...); arrow(...); vector(...); circle(...); rectangle(...); polygon(...); plot(...); route(...); path(...); curve(...); surface(...); text(...); ruler(...); svg(...); image(...); cell(...); connector(...); }",
        "Scene and Object method set",
        "The factory surface shared by SceneBuilder and every ObjectHandle.",
    ),
    api(
        "Types",
        "ObjectHandle",
        "interface ObjectHandle extends Handle, ObjectFactory { label(options: TextOptions): ObjectHandle; moveTo(...): this; nextTo(...): this; alignTo(...): this; }",
        "protected object userdata",
        "A same-Scene object reference with child factories, an Object-only label helper, and bounds-based layout methods.",
    ),
    api(
        "Types",
        "GroupHandle",
        "interface GroupHandle extends ObjectHandle { arrange(...): this; arrangeGrid(...): this; }",
        "protected Group userdata",
        "An ObjectHandle specialized with direct-child linear and grid layout.",
    ),
    api(
        "Types",
        "SpaceHandle",
        "interface SpaceHandle extends ObjectHandle { cell(options: CellOptions): ObjectHandle; cell(callback: CellSampler, options?: CellSampleOptions): GroupHandle; voxel(callback: VoxelSampler, options?: VoxelSampleOptions): GroupHandle; }",
        "protected Space userdata",
        "An ObjectHandle representing a visible matrix coordinate space with bounded authoring-time Cell and Voxel sampling.",
    ),
    api(
        "Types",
        "CellSampler / VoxelSampler",
        "type CellSampler = (x: number, y: number, time: number) => Color; type VoxelSampler = (x: number, y: number, z: number, time: number) => Color;",
        "function(x, y, time) / function(x, y, z, time)",
        "Synchronous authoring-time callbacks. Time is seconds; callbacks are discarded after their bounded samples are retained.",
    ),
    api(
        "Types",
        "CellSampleOptions / VoxelSampleOptions",
        'interface CellSampleOptions { mode?: "full" | "padd"; padding?: number; duration?: number; fps?: number; }',
        "table",
        "Duration defaults to zero for one static frame; fps defaults to 30. Positive duration advances the Scene and retained frames interpolate linearly.",
    ),
    api(
        "Types",
        "GroupOptions",
        "interface GroupOptions extends Style { matrix?: Mat4; }",
        "table",
        "Initial semantic-container style and local-to-parent affine matrix.",
    ),
    api(
        "Types",
        "SpaceOptions",
        'interface SpaceOptions { x?: Range; y?: Range; z?: Range; matrix?: Mat4; axis_x?: Color; axis_y?: Color; axis_z?: Color; numbers?: boolean; number_mode?: "fixed" | "relative"; number_size?: number; number_color?: Color; }',
        "table",
        "The matrix maps local cells into the parent Object or global Scene. Fixed numbers preserve local values; relative numbers follow each transformed basis length.",
    ),
    api(
        "Types",
        "RectangleOptions",
        "interface RectangleOptions extends Style { center?: WorldVector; size?: Vec2; corner?: number; }",
        "table",
        "Rectangle center, positive width/height, and non-negative corner radius in receiver-local units.",
    ),
    api(
        "Types",
        "PathOptions",
        "interface PathOptions extends Style { commands: PathCommand[]; samples?: number; }",
        "table",
        "A single contour beginning with move, followed by line/quadratic/cubic commands and an optional final close. Samples controls subdivisions per curved command.",
    ),
    api(
        "Types",
        "CurveOptions",
        "interface CurveOptions extends Style { from: WorldVector; control1: WorldVector; control2: WorldVector; to: WorldVector; samples?: number; }",
        "table",
        "A cubic Bézier curve sampled deterministically in receiver-local 2D or 3D coordinates.",
    ),
    api(
        "Types",
        "SurfaceOptions",
        'interface SurfaceOptions extends Style { points: WorldVector[]; size: [number, number]; mode?: "solid" | "mesh" | "solid_mesh"; shading?: boolean; }',
        "table",
        "A row-major sampled point lattice with at least two columns and two rows.",
    ),
    api(
        "Types",
        "TextOptions",
        'interface TextOptions extends Style { text: string; point?: WorldVector; size?: number; align?: Vec2; font?: string; role?: "h1" | "h2" | "h3" | "text" | "code"; orientation?: "billboard" | "plane"; }',
        "table",
        "Omitted font, size, and color resolve from the semantic role. Billboard size is in pixels; Plane size is in world units and follows the receiver transform.",
    ),
    api(
        "Types",
        "ConnectorOptions",
        "interface ConnectorOptions extends Style { padding?: number; tail?: number; tip?: number; }",
        "table",
        "Non-negative world-unit endpoint padding and pixel-sized arrow caps for a derived connector.",
    ),
    api(
        "Types",
        "AnimationSpec",
        "type AnimationSpec = { target: ObjectHandle; shift?: WorldVector; transform?: Mat4; opacity?: number; stroke?: Color; fill?: Color; dash_offset?: number; tail?: number; tip?: number; }",
        "descriptor table",
        "Requires at least one animated property; shift and transform are mutually exclusive and unavailable for Connector targets. dash_offset requires a dashed target; tail and tip require marker-bearing geometry. Targets in one play call must be distinct.",
    ),
    api(
        "Types",
        "FadeOptions",
        "type FadeOptions = { shift?: WorldVector; scale?: number; duration?: number; easing?: AnimCurve; curve?: AnimCurve; }",
        "table",
        "Directional FadeIn/FadeOut options. Use either easing or curve; scale must be finite and positive.",
    ),
    api(
        "Types",
        "IndicateOptions",
        "type IndicateOptions = { color?: Color; scale?: number; duration?: number; easing?: AnimCurve; curve?: AnimCurve; }",
        "table",
        "Temporary highlight options. Use either easing or curve; scale must be finite and greater than one.",
    ),
    api(
        "Types",
        "CreateDirection",
        'type CreateDirection = "forward" | "reverse" | "clockwise" | "counterclockwise"',
        "string",
        "Path traversal direction for Create, Uncreate, and Write. On open paths clockwise/reverse and counterclockwise/forward are aliases.",
    ),
    api(
        "Types",
        "ImageOptions",
        'type ImageOptions = ({ asset: string } | { pixels: Color[]; size: [number, number] }) & { center?: WorldVector; width?: number; filter?: "bilinear" | "nearest"; }',
        "table",
        "Aspect-preserving receiver-local image placement backed by a decoded Asset or inline row-major pixel colors.",
    ),
    api(
        "Types",
        "CellOptions",
        'interface CellOptions { origin?: WorldVector; size: [number, number]; mode?: "full" | "padd"; padding?: number; depth?: number; texture?: string; source?: CellRegion; destination?: CellRegion; patches?: CellPatch[]; }',
        "table",
        "A dense batch of image-processing cells. Padd defaults to five percent when selected.",
    ),
    api(
        "Types",
        "WorldVector",
        "type WorldVector = Vec2 | Vec3",
        "2- or 3-number array",
        "Two components are lifted to z=0; storage and rendering remain unified.",
    ),
    api(
        "Types",
        "Vec2",
        "type Vec2 = readonly [number, number] | {x: number; y: number}",
        "{x,y}",
        "Two-component input or camera delta.",
    ),
    api(
        "Types",
        "Vec3",
        "type Vec3 = readonly [number, number, number] | {x: number; y: number; z: number}",
        "{x,y,z}",
        "World-space vector value.",
    ),
    api(
        "Types",
        "Mat4",
        "type Mat4 = readonly [number × 16]",
        "16-number array",
        "Row-major affine world matrix.",
    ),
    api(
        "Types",
        "Range",
        "type Range = readonly [number, number, number] | {min: number; max: number; step: number}",
        "{min, max, step}",
        "Inclusive coordinate range.",
    ),
    api(
        "Animation curves",
        "tmath.animCurve.preset",
        "tmath.animCurve.preset(preset: AnimCurvePreset, strength?: number): AnimCurve",
        "{preset=name, strength=value}",
        "Build a validated named curve. Strength 0 is linear, 1 is the original curve, and 2 doubles its timing character.",
        "AnimCurve",
    ),
    api(
        "Animation curves",
        "tmath.animCurve.cubicBezier",
        "tmath.animCurve.cubicBezier(x1: number, y1: number, x2: number, y2: number, strength?: number): AnimCurve",
        "{bezier={x1,y1,x2,y2}, strength=value}",
        "Build a deterministic custom timing curve. X controls are limited to 0..1 and y controls to -2..2.",
        "AnimCurve",
    ),
    api(
        "Animation curves",
        "tmath.animCurve.reverse",
        "tmath.animCurve.reverse(curve: AnimCurve): AnimCurve",
        "{preset=name, strength=value, reverse=true}",
        "Return a validated timing curve sampled as 1 - curve(1 - t). Reversing twice restores the original curve.",
        "AnimCurve",
    ),
    api(
        "Types",
        "AnimCurvePreset",
        'type AnimCurvePreset = Easing | "gentle" | "snappy" | "back" | "bounce" | "elastic"',
        "string",
        "Named timing curves accepted directly or through the preset factory.",
    ),
    api(
        "Types",
        "AnimCurve",
        "type AnimCurve = AnimCurvePreset | {preset: AnimCurvePreset; strength: number; reverse?: boolean} | {bezier: [number, number, number, number]; strength: number; reverse?: boolean}",
        "string or table",
        "Animation timing with optional effect strength and exact reverse playback.",
    ),
    api(
        "Types",
        "Easing",
        'type Easing = "linear" | "smooth" | "ease_in" | "ease_out" | "ease_in_out"',
        "string",
        "Backward-compatible subset of AnimCurvePreset.",
    ),
    api(
        "Types",
        "StrokeDash",
        "type StrokeDash = readonly [number] | readonly [number, number] | readonly [number, number, number] | readonly [number, number, number, number]",
        "{on, off, ...} (1 to 4 non-negative values)",
        "A repeating stroke dash pattern measured in output pixels; dash_offset shifts its phase.",
    ),
    api(
        "Types",
        "Style",
        "interface Style { id?: string; color?: Color; stroke?: Color; fill?: Color; width?: number; gradient?: boolean | Color; radius?: number; dash?: StrokeDash; dash_offset?: number; opacity?: number; progress?: number; layer?: number; }",
        "table",
        "Shared object identity and paint fields. Shape gradient false overrides a Theme gradient; true uses its end stop; a Color supplies an explicit end stop.",
    ),
];
